import json, pathlib
j=json.load(open('/tmp/vaeroex-stage1-control-inventory.json'))
controls={
'/app':'Overview; Business Health instrument/trend/drawer; analyze current evidence, regenerate/retry, save analysis; evidence links; signals; navigation.',
'/app/[module]':'Guarded coming-soon shell for workflows/intake/unknown single segments; dashboard and global-search links; actions/briefings/generated return not-found.',
'/app/account/subscription':'Status/plan/access/usage; manage Stripe billing, pricing, already-purchased, billing email.',
'/app/admin':'Admin navigation, customer queue, manage links, metrics.',
'/app/admin/ai-trust':'Trust/evidence/provider status filters, range/sort selections and detail expansion (AiTrustDashboard).',
'/app/admin/ai-usage':'Usage filter, all/recent links, run details, show-more/reduce controls.',
'/app/admin/audit-logs':'Search, log-details views, show-more/reduce for audit and error logs.',
'/app/admin/customers':'Search/status/plan/sort filters, company table links, previous/next pagination, activation review.',
'/app/admin/customers/[workspaceId]':'Overview/subscription/access/agreement/activity tabs; subscription editor; workspace access changes; lifecycle controls; agreement links.',
'/app/admin/subscriptions':'Search/status/sort/apply/clear; previous/next; activation-review forms; manual activation; customer manage links.',
'/app/admin/support-requests':'Search/status/view filters; priority/status update; archive/restore; duplicate; confirmed delete.',
'/app/admin/workspace-agreements':'Search/date filters; view agreement.',
'/app/admin/workspace-agreements/[agreementId]':'Agreement rendering; PDF/print/download through agreement components; resend admin email.',
'/app/admin/workspaces':'Queue filters, table customer/manage links, pagination.',
'/app/admin/nvidia-qualification':'Internal qualification evidence view and its linked run/result controls; production mutation/cost execution not attempted.',
'/app/admin/nvidia-qualification/stage-two':'Internal Stage 2 qualification evidence/status; execution not attempted.',
'/app/admin/nvidia-qualification/stage-three-a':'Internal Stage 3A qualification evidence/status; execution not attempted.',
'/app/admin/nvidia-qualification/stage-three-b':'Internal Stage 3B qualification evidence/status; execution not attempted.',
'/app/agents':'Guarded permanent redirect to /app/intelligence.',
'/app/ask':'Flag-dependent conversational interface (prompts/history/response evidence), or redirect to Intelligence; legacy query rejection.',
'/app/assets':'Create asset/check; two managed-record lists (search/filter/sort/date/folder/page/details/edit/archive/hide/restore/duplicate); assets/checks relation.',
'/app/checklist-runs':'Guarded permanent redirect to /app.',
'/app/checklists':'Guarded permanent redirect to /app.',
'/app/crm':'Read-only customer context; Evidence/Intelligence links and compact record disclosures.',
'/app/files':'Legacy file/query normalization and permanent redirect to Evidence/detail.',
'/app/form-submissions':'Select form; submitter/summary/priority/follow-up inputs; create; managed-record search/filter/folder/page/details/edit/lifecycle controls.',
'/app/forms':'Create name/type/description/custom-field schema/public setting; managed record list; form-detail links.',
'/app/forms/[id]':'Back link; internal submission form; stored schema readout; submission details.',
'/app/help':'Search; category filters; article disclosure/help links; support/trust links.',
'/app/help/release-notes':'Release-note reading and navigation links.',
'/app/help/trust':'Trust documents and contact/navigation links.',
'/app/integrations':'DEPLOYED ONLY: Square/QBO/Google Sheets provider cards; role/flag/availability states; manage/view setup links. Local generic catch-all exists but feature implementation absent.',
'/app/integrations/square':'DEPLOYED ONLY: Square source/evidence data and settings/navigation; provider controls discovered transitively. No external sync tested.',
'/app/intelligence':'Finding type/category/filter/selection; details/explanation/evidence tabs; explanation/run/save/retry; acknowledge/dismiss/snooze/reopen lifecycle; briefings links.',
'/app/intelligence/briefings':'Weekly/monthly availability, generation/update and view cards.',
'/app/intelligence/briefings/[type]':'Current weekly/monthly briefing; save, download/print where exposed; evidence links; unsupported type not-found.',
'/app/issues':'Create issue; owner/role/department/date where present; managed-record list and lifecycle.',
'/app/kpis':'Timeline/custom dates/status/show-more; overview/compare/detail/records tabs; compare metrics/modes; target recommendation accept/undo; semantic suggest/accept; value edit; create KPI; share; managed-record list.',
'/app/kpis/profit-leakage':'Eligible evidence/findings readout; Evidence navigation.',
'/app/kpis/settings':'Owner/admin settings forms: target/weight/name/semantics/category/units/definition/chart/color/visibility; legacy color confirmation; non-admin read-only branch.',
'/app/legal/agreements/[agreementId]':'Scoped legal agreement view/PDF/print/navigation.',
'/app/notifications':'Guarded permanent redirect to /app.',
'/app/people':'Guarded permanent redirect to /app.',
'/app/reports':'Saved-analysis type/search filters; select all/clear; confirmed single/bulk delete; view analysis/briefing. Deployed reference additionally pages loaded cards and discloses 300-row cap.',
'/app/reports/[id]':'Validated immutable saved artifact; evidence/source links; back navigation; incompatible/retired records redirect.',
'/app/settings':'Theme controls; password/confirmation; local QBO/Sheets connection status/navigation; deployed separate Integrations link.',
'/app/settings/integrations/google-sheets':'Local connect/entity/spreadsheet/tab/header/mapping/manual sync/disconnect. Deployed owner-only authorization/reconnect/recovery, entity-create, mapping approval, automatic/manual sync status and run review; extensive baseline drift.',
'/app/settings/integrations/quickbooks':'DEPLOYED ONLY: owner management; connect/reconnect/cancel; freshness; stored-data and accounting-authority links.',
'/app/settings/integrations/quickbooks/accounting':'DEPLOYED ONLY: accounting authority status/detail and controls; inspect baseline for permitted owner flow before any mutation.',
'/app/settings/integrations/quickbooks/data':'DEPLOYED ONLY: stored provider data list, filters and details/navigation.',
'/app/settings/integrations/quickbooks/disconnect':'Role-gated connection list; required confirmation checkbox; disconnect; back link; requested/in-progress/failure states.',
'/app/setup':'Subscription gate; legal agreement/intake workspace-creation form; confirmation and pending/error states.',
'/app/sops':'Create SOP title/department/category/body/status/version; related-source links; managed-record list.',
'/app/sources':'Evidence/business-notes/legal tabs; search/status/date/lifecycle; file upload, analyze/retry, review/confirm/discard import; preview/download originals; source links; knowledge edit/lifecycle/bulk; Business Notes compose/review; agreements.',
'/app/sources/[fileId]':'Source detail tabs, original preview/download, extraction/analyze/retry, import mapping/approval, learned knowledge, KPIs/findings/source lineage; file-not-found.',
'/app/support':'Name/email/category/priority/subject/message support form; support/billing mail links.',
}
by={}
for row in j['routes']:by.setdefault(row['route'],{})[row['snapshot']]=row
out=['# Stage 1 route and control coverage (assessment evidence)', '',
'Generated from the actual working tree and deployed-reference commit `d91be079c7beb0b6f21a4c5e6b451f90ca06e035`. This is a static JSX control-template census, not a claim that each control was exercised. Each dynamically repeated record/link remains one template. Shared shell controls are included separately.','',
'Runtime status `blocked` means authenticated browser and persisted-result testing requires isolated accounts and a schema-matched isolated backend; no customer data or production mutations were used. Static guard checks and isolated fault-injection checks below use their own statuses. `Untested` exclusions are explicit.','',
'| Route | Working / deployed control templates | Runtime status | Controls / states to verify |','|---|---:|---|---|']
for route,entry in sorted(by.items()):
 wc=entry.get('working-tree',{}).get('controlTemplates','—');dc=entry.get('deployed-reference-d91be079',{}).get('controlTemplates','—')
 excluded='easter-egg' in route
 note='Excluded from functional audit: unrelated Easter Egg/Civilization feature; shared auth/admin boundary still inventoried.' if excluded else controls.get(route,'See control census.')
 out.append(f'| `{route}` | {wc} / {dc} | '+('untested (excluded)' if excluded else 'blocked')+f' | {note} |')
out += ['', 'Shared controls: workspace switcher, sign out, desktop/mobile primary/admin navigation, search dialog/shortcut/query/results, theme, activity/progress/toasts, legal acceptance gate, contextual help, loading/error/not-found boundaries. These occur under `SHARED_WORKSPACE_SHELL` / `SHARED_ADMIN_SHELL` in the CSV. Their live desktop/mobile/keyboard/session-switch tests remain blocked.', '',
'| Verification item | Status | Evidence and limit |','|---|---|---|',
'| Static page/control census | passed | 54 working-tree + 59 deployed route patterns; 3,510 per-route control occurrences; 1,887 unique snapshot/file/line templates. This establishes inventory only. |',
'| Asset-check second-write failure handling | failed | Executed original action with failed and zero-row mocked parent update; both return success. No live DB used. |',
'| Schema-backed internal form persistence | failed | Original action ignores custom fields and stores only generic summary/priority/follow-up. Isolated action capture. |',
'| Replayed issue-create deduplication | failed (application layer) | Two identical original-action invocations reach two inserts. Real concurrent browser/persistence remains untested. |',
'| Retired routes static guard/redirect mapping | passed | Checklists/checklist-runs/notifications/people → Overview; tasks → Evidence; agents → Intelligence. Redirect runtime/session behavior remains blocked. |',
'| Direct unauthenticated route behavior | blocked (subagent) | Root owns anonymous local/deployed probes; integrate those results here. |',
'| Owner/admin/manager/staff/viewer form-state behavior | blocked | No isolated authenticated backend available to this subagent. Server/RLS code reviewed, not an authorization-request pass. |',
'| Desktop/mobile layout, keyboard, failure/retry/repeated clicks | blocked | Static responsive classes/handlers inspected; no comprehensive authenticated browser exercise. Modal focus concern recorded. |',
'| Real upload→extract→approve→persist→cite→save→export | blocked | Requires isolated storage, provider mocks/test credentials and schema-matched DB. No mutation performed. |',
'| OAuth expired/revoked/reconnect, sync overlap/partial-failure | blocked | Local and deployed implementations differ materially; source inventory only. |',
'| Unrelated marketing/Civilization behavior | untested | Explicitly outside requested scope. |', '',
'Detailed census: `/tmp/vaeroex-stage1-control-coverage.csv` (one row per route/control template, with snapshot, source file/line, labels, handlers/attributes, status and basis); full JSON and generator are adjacent. Root should copy these into the persistent audit evidence directory and assign final finding IDs.']
pathlib.Path('/tmp/vaeroex-stage1-routes.md').write_text('\n'.join(out)+'\n')
