import Link from "next/link";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

const moduleCopy: Record<string, { title: string; description: string }> = {
  intake: {
    title: "Business intake",
    description: "Capture setup answers, operational problems, current tools, and ideal outcomes."
  },
  workflows: {
    title: "Workflow builder",
    description: "Map triggers, owners, steps, handoffs, and review points for repeatable operations."
  },
  forms: {
    title: "Forms",
    description: "Create operational forms, public links, and submission summaries."
  },
  "form-submissions": {
    title: "Form submissions",
    description: "Review submissions, Vaeroex summaries, priorities, and confirmed follow-up tasks."
  },
  checklists: {
    title: "Checklists",
    description: "Create recurring readiness, completion, manager review, and handoff checklists."
  },
  "checklist-runs": {
    title: "Checklist runs",
    description: "Review checklist completions, notes, responses, and readiness history."
  },
  tasks: {
    title: "Tasks",
    description: "Track follow-up tasks, due dates, owners, statuses, and priorities."
  },
  issues: {
    title: "Issue tracker",
    description: "Log bottlenecks, root causes, recommended fixes, and manager review items."
  },
  assets: {
    title: "Asset tracker",
    description: "Track readiness, ownership, check history, and equipment needing attention."
  },
  people: {
    title: "People",
    description: "Keep team roles, departments, status, and accountability visible."
  },
  sops: {
    title: "SOP library",
    description: "Create, edit, and later generate SOP drafts with Vaeroex after confirmation."
  },
  reports: {
    title: "Reports",
    description: "Weekly operations reports and bottleneck summaries will show Generated by Vaeroex."
  },
  agents: {
    title: "Vaeroex Hub",
    description: "Vaeroex can help you turn messy operations into clear systems."
  },
  settings: {
    title: "Settings",
    description: "Manage workspace profile, roles, branding, integration settings, and compliance notice."
  }
};

type ModulePageProps = {
  params: Promise<{
    module: string;
  }>;
};

export default async function ModulePlaceholderPage({ params }: ModulePageProps) {
  await requireWorkspacePage();

  const { module } = await params;
  const copy = moduleCopy[module] || {
    title: "Operations module",
    description: "This module is not available yet. Return to the dashboard to continue with active operations tools."
  };

  return (
    <section className="rounded-lg border border-line bg-white p-6 shadow-panel">
      <p className="text-sm font-semibold uppercase tracking-wide text-vaeroex-blue">Phase 3 module</p>
      <h2 className="mt-2 text-2xl font-semibold">{copy.title}</h2>
      <p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{copy.description}</p>
      {module === "agents" ? (
        <div className="mt-5 rounded-lg border border-blue-100 bg-vaeroex-soft p-4 text-sm text-vaeroex-navy">
          Ask Vaeroex will use the configured Vaeroex prompt and save structured results for review.
        </div>
      ) : null}
      <Link
        href="/app"
        className="mt-6 inline-flex rounded-lg bg-vaeroex-blue px-4 py-2 text-sm font-semibold text-white"
      >
        Back to dashboard
      </Link>
    </section>
  );
}
