steps:
  - name: gcr.io/cloud-builders/docker@sha256:f8b08c609fdc392ee6827ff3e1725e4980f7d96bde9f76f4695086405c96c147
    args:
      - build
      - --file
      - services/external-integrations-qbo/Dockerfile
      - --tag
      - ${_IMAGE}
      - --build-arg
      - QBO_SOURCE_COMMIT=${_SOURCE_COMMIT}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
