"use strict";
/* eslint-disable @typescript-eslint/no-require-imports -- Standalone Node CommonJS qualification CLI. */
// Permanent local qualification. All credentials, certificates and database
// catalogs below are generated by this run. No remote/credential CLI exists.
const fs = require("node:fs");
const path = require("node:path");
const net = require("node:net");
const { spawn } = require("node:child_process");
if (process.argv.length !== 2) { process.stdout.write('{"outcome":"remote_inputs_rejected"}\n'); process.exit(2); }
const { createFixture, failed, command, hash, env, pgRoot, admin, target, capability } = (() => {
  try { return require("./fixture.cjs"); } catch { process.stdout.write('{"outcome":"local_dependencies_denied"}\n'); process.exit(2); }
})();
for (const key of Object.keys(process.env)) delete process.env[key];
Object.assign(process.env, env);
global.fetch = () => failed("network_not_authorized");
const passed = [];
let stage = "bootstrap", fixture, failure, linuxMlockMeasured = false;
const secrets = [];
const check = (condition, name) => { if (!condition) failed(name); passed.push(name); };
const pause = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));
const deadline = async (predicate, maximum = 5000) => {
  const until = Date.now() + maximum;
  while (!await predicate()) { if (Date.now() >= until) failed("synthetic_observer_timeout"); await pause(20); }
};
function build(root) {
  const source = path.resolve(__dirname, "../native.c"), synthetic = path.join(root, "native-synthetic"), release = path.join(root, "native-release");
  const flags = ["-std=c11", "-Wall", "-Wextra", "-Werror", "-pthread", "-I" + path.join(pgRoot, "include"), "-L" + path.join(pgRoot, "lib"),
    "-Wl,-rpath," + path.join(pgRoot, "lib"), source, "-lpq"];
  command("/usr/bin/cc", [...flags, "-DVAEROEX_SYNTHETIC_ONLY", "-o", synthetic]);
  command("/usr/bin/cc", [...flags, "-o", release]);
  return { synthetic, release, sourceSha256: hash(source), syntheticSha256: hash(synthetic), releaseSha256: hash(release) };
}
function worker(binary, operation, roleOid, options = {}) {
  const host = options.host ?? fixture.socket, port = options.port ?? fixture.port;
  if (host !== fixture.socket && host !== "127.0.0.1") failed("worker_remote_target");
  const args = [operation, host, String(port), "postgres", options.admin ?? admin, options.target ?? target, capability,
    options.systemId ?? fixture.systemId, fixture.databaseOid, host === "127.0.0.1" ? fixture.cert : "-",
    "synthetic_intent_001", String(roleOid), "synthetic_approval_001"];
  return new Promise((resolve, reject) => {
    const child = spawn(binary, args, { env: { PATH: env.PATH, LANG: env.LANG, LC_ALL: env.LC_ALL }, stdio: ["ignore", "pipe", "pipe", "pipe", "pipe", "pipe", "pipe"] });
    let stdout = "", stderrBytes = 0, candidate = "", final = null, ready = 0, secretFrames = 0, settled = false, failedAt;
    const started = Date.now();
    const fail = name => { if (settled || failedAt) return; failedAt = name; child.kill("SIGKILL"); clearTimeout(timer); };
    const timer = setTimeout(() => fail("worker_watchdog_exceeded"), 20000);
    for (const stream of [child.stdin, ...child.stdio.slice(3)]) stream?.on("error", () => undefined);
    child.once("error", () => fail("worker_spawn"));
    child.stderr.on("data", bytes => {
      stderrBytes += bytes.length;
      // Classification only, never forward the actual diagnostic bytes.
      const kind = bytes.includes(Buffer.from("dyld")) ? "loader" : bytes.includes(Buffer.from("NOTICE")) ? "notice"
        : bytes.includes(Buffer.from("WARNING")) ? "warning" : bytes.includes(Buffer.from("FATAL")) ? "fatal" : "other";
      if (stderrBytes) fail("worker_raw_diagnostics_" + kind);
    });
    child.stdout.on("data", bytes => {
      stdout += bytes.toString(); if (stdout.length > 1024) return fail("worker_output_bound");
      while (stdout.includes("\n")) {
        const end = stdout.indexOf("\n"), line = stdout.slice(0, end); stdout = stdout.slice(end + 1);
        if (line === '{"phase":"ready"}') {
          if (++ready > 1) return fail("worker_duplicate_ready");
          if (options.cancelReady) child.kill("SIGTERM");
        } else {
          const match = /^\{"outcome":"(?:(assigned|prepared|fenced|activated|inspected|authenticated)","committed":true,"role_oid":"([0-9]{1,10})"|(failed|uncertain|policy_blocked)")\}$/.exec(line);
          if (!match || final !== null) return fail("worker_output_allowlist");
          final = match[1] ?? match[3];
        }
      }
    });
    child.stdio[4].on("data", bytes => {
      candidate += bytes.toString("ascii");
      if (candidate.length > 129 || !/^[0-9a-f]*\n?$/.test(candidate)) return fail("private_candidate_frame");
      if (!candidate.endsWith("\n")) return;
      if (++secretFrames !== 1 || !/^[0-9a-f]{128}\n$/.test(candidate)) return fail("private_candidate_duplicate");
      const password = candidate.slice(0, -1); secrets.push(password);
      void Promise.resolve().then(async () => {
        if (options.onCandidate) await options.onCandidate(password, child);
        if (options.cancelCandidate) child.kill("SIGTERM");
        else if (!options.withholdAck) child.stdio[5].end("STORED\n");
      }).catch(() => fail("private_candidate_observer"));
    });
    if (!options.holdAdmin) child.stdio[3].end("\n");
    if (options.password) {
      if (!/^[a-f0-9]{128}$/.test(options.password)) return fail("synthetic_auth_frame");
      child.stdio[6].end(options.password + "\n");
    } else child.stdio[6].end();
    child.once("close", (code, signal) => {
      if (settled) return; settled = true; clearTimeout(timer);
      if (failedAt) return reject(Object.assign(new Error("synthetic_worker_failed"), { safeStage: failedAt }));
      if (stdout || stderrBytes) return reject(Object.assign(new Error("synthetic_output_failed"), { safeStage: "worker_output_incomplete" }));
      resolve({ outcome: final, code, signal, ready, secretFrames, password: candidate ? candidate.slice(0, -1) : null, elapsed: Date.now() - started });
    });
  });
}
async function role() {
  return (await fixture.control.query("SELECT oid::text,rolcanlogin,rolsuper,rolcreatedb,rolcreaterole,rolreplication,rolbypassrls,rolpassword FROM pg_authid WHERE rolname=$1", [target])).rows[0];
}
async function privacy(offsets, name) {
  await pause(100);
  const bytes = Buffer.concat([fixture.logBytes(offsets), fixture.statBytes()]);
  check(!bytes.includes(Buffer.from("SCRAM-SHA-256$")), name + "_no_verifier_in_log_or_pgstat_disk");
  for (const secret of secrets) check(!bytes.includes(Buffer.from(secret)), name + "_no_password_in_log_or_pgstat_disk");
  const queries = (await fixture.control.query("SELECT query FROM pg_stat_statements")).rows;
  check(queries.every(row => !row.query.includes("SCRAM-SHA-256$") && secrets.every(secret => !row.query.includes(secret))), name + "_no_payload_in_query_statistics");
  return bytes;
}
async function proxy() {
  const peers = new Set(); let suppress = false;
  const server = net.createServer(incoming => {
    const upstream = net.connect({ host: "127.0.0.1", port: fixture.port });
    peers.add(incoming); peers.add(upstream);
    for (const socket of [incoming, upstream]) { socket.on("error", () => { incoming.destroy(); upstream.destroy(); }); socket.on("close", () => peers.delete(socket)); }
    incoming.on("data", bytes => upstream.write(bytes));
    upstream.on("data", bytes => { if (!suppress) incoming.write(bytes); });
    incoming.on("end", () => upstream.end()); upstream.on("end", () => incoming.end());
  });
  await new Promise((resolve, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", resolve); });
  return { port: server.address().port, suppressReplies: () => { suppress = true; }, close: async () => { for (const socket of peers) socket.destroy(); await new Promise(resolve => server.close(resolve)); } };
}
async function main() {
  fixture = await createFixture(); const binaries = build(fixture.root);
  const source = fs.readFileSync(path.resolve(__dirname, "../native.c"), "utf8");
  check(source.indexOf("munlock(admin_password") > source.lastIndexOf("wipe(password"), "shared_page_admin_unlock_occurs_only_after_candidate_wipe");
  check((await fixture.control.query("SHOW server_version")).rows[0].server_version === "17.6", "exact_local_postgres_17_6");
  check((await fixture.control.query("SHOW listen_addresses")).rows[0].listen_addresses === "127.0.0.1", "only_loopback_tcp_and_private_socket");
  stage = "positive_controls";
  const marker = "SYNTHETIC_NATIVE_POSITIVE_ONLY_" + Date.now();
  const start = fixture.logOffsets();
  await fixture.control.query(`CREATE ROLE synthetic_capture_positive NOLOGIN PASSWORD '${marker}'`);
  await pause(100);
  check(fixture.logBytes(start).includes(Buffer.from(marker)), "unsafe_plaintext_log_positive_control");
  check(fixture.statBytes().includes(Buffer.from(marker)), "unsafe_pgstat_disk_positive_control");
  const psql = command(path.join(pgRoot, "bin/psql"), ["-X", "-w", "-h", fixture.socket, "-p", String(fixture.port), "-U", admin, "-d", "postgres", "-c", "\\password synthetic_capture_positive"], { input: marker + "\n" + marker + "\n" });
  check(!psql.includes(marker), "native_password_does_not_echo_positive_control");
  await pause(100);
  check(fixture.logBytes(start).includes(Buffer.from("SCRAM-SHA-256$")), "unsafe_native_verifier_log_positive_control");
  check(fixture.statBytes().includes(Buffer.from("SCRAM-SHA-256$")), "unsafe_native_verifier_pgstat_disk_positive_control");
  const activity = await fixture.connect(), activityMarker = "SYNTHETIC_NATIVE_ACTIVITY_ONLY";
  const sleeping = activity.query(`SELECT pg_sleep(0.3) /* ${activityMarker} */`);
  await deadline(async () => (await fixture.control.query("SELECT EXISTS (SELECT FROM pg_stat_activity WHERE query LIKE $1) AS present", ["%" + activityMarker + "%"])).rows[0].present);
  check(true, "unsafe_activity_capture_positive_control");
  await sleeping; await activity.end();
  const debugStart = fixture.logOffsets(), debugMarker = "SYNTHETIC_NATIVE_DEBUG_ONLY";
  await fixture.control.query("SET log_statement='none'; SET debug_print_parse=on");
  await fixture.control.query(`ALTER ROLE synthetic_capture_positive PASSWORD '${debugMarker}'`);
  await fixture.control.query("SET debug_print_parse=off; RESET log_statement");
  await pause(100);
  check(fixture.logBytes(debugStart).includes(Buffer.from(debugMarker)), "unsafe_debug_parse_capture_positive_control");
  // Use a separate pristine cluster for protected cases: resetting a statistics
  // view does not establish that an append-only query-text file erased old bytes.
  await fixture.stop();
  check(fixture.statBytes().includes(Buffer.from("SCRAM-SHA-256$")), "unsafe_verifier_persists_in_saved_statistics_positive_control");
  fixture = await createFixture();
  stage = "release_closed";
  const release = await worker(binaries.release, "inspect", 0, { holdAdmin: true });
  check(release.outcome === "policy_blocked" && release.secretFrames === 0 && release.elapsed < 3000, "release_refuses_before_private_input_or_network");
  stage = "prepare";
  let offsets = fixture.logOffsets();
  const prepared = await worker(binaries.synthetic, "prepare", 0);
  check(prepared.outcome === "prepared" && prepared.secretFrames === 0, "prepare_without_credential_generation");
  let current = await role(); const oid = current.oid;
  check(!current.rolcanlogin && !current.rolsuper && !current.rolcreatedb && !current.rolcreaterole && !current.rolreplication && !current.rolbypassrls && current.rolpassword === null, "prepared_exact_unprivileged_nologin_role");
  check((await worker(binaries.synthetic, "inspect", oid)).outcome === "inspected", "capability_membership_does_not_false_positive_direct_authority");
  await privacy(offsets, "prepare");
  stage = "direct_authority_denials";
  await fixture.control.query("CREATE TABLE public.synthetic_authority_data(value integer); CREATE FUNCTION public.synthetic_authority_probe() RETURNS integer LANGUAGE sql IMMUTABLE AS 'SELECT 1'");
  for (const [name, setup, undo] of [
    ["table_acl", `GRANT SELECT ON public.synthetic_authority_data TO ${target}`, `REVOKE SELECT ON public.synthetic_authority_data FROM ${target}`],
    ["function_acl", `GRANT EXECUTE ON FUNCTION public.synthetic_authority_probe() TO ${target}`, `REVOKE EXECUTE ON FUNCTION public.synthetic_authority_probe() FROM ${target}`],
    ["object_owner", `ALTER TABLE public.synthetic_authority_data OWNER TO ${target}`, `ALTER TABLE public.synthetic_authority_data OWNER TO ${admin}`],
    ["database_role_setting", `ALTER ROLE ${target} IN DATABASE postgres SET work_mem='1MB'`, `ALTER ROLE ${target} IN DATABASE postgres RESET ALL`]
  ]) {
    await fixture.control.query(setup); offsets = fixture.logOffsets();
    const denied = await worker(binaries.synthetic, "assign", oid);
    check(denied.outcome === "failed" && denied.secretFrames === 0 && denied.ready === 0, name + "_denied_before_candidate");
    await privacy(offsets, name); await fixture.control.query(undo);
    check((await worker(binaries.synthetic, "inspect", oid)).outcome === "inspected", name + "_fixture_reset_restores_exact_scope");
  }
  stage = "pre_secret_negatives";
  const privileged = await fixture.connect("synthetic_privileged");
  check(!(await privileged.query("SELECT has_parameter_privilege(current_user,'log_statement','SET') AS allowed")).rows[0].allowed,
    "native_parameter_acl_false_is_not_effective_permission_proof");
  await privileged.query("SET log_statement='all'");
  check((await privileged.query("SHOW log_statement")).rows[0].log_statement === "all", "supautils_actual_allowed_set_succeeds");
  let permissionState;
  try { await privileged.query("SET track_activities=off"); } catch (error) { permissionState = error.code; }
  check(permissionState === "42501", "supautils_unlisted_activity_control_rejects");
  await privileged.end();
  for (const [name, operation, expectedOid, options] of [
    ["missing_role", "assign", oid, { target: "square_sandbox_missing_broker" }],
    ["wrong_oid", "assign", "4294967290", {}], ["wrong_system", "assign", oid, { systemId: "1234567890123456789" }],
    ["permission", "assign", oid, { admin: "synthetic_unprivileged" }],
    ["extension_permission_not_native_acl", "assign", oid, { admin: "synthetic_privileged" }]
  ]) {
    offsets = fixture.logOffsets();
    const result = await worker(binaries.synthetic, operation, expectedOid, options);
    check(["failed", "policy_blocked"].includes(result.outcome) && result.secretFrames === 0, name + "_denies_before_secret");
    await privacy(offsets, name);
  }
  for (const table of ["square_remote_sandbox_binding", "square_gcp_callback_binding"]) {
    await fixture.control.query(`INSERT INTO private.${table}(broker_login,enabled) VALUES($1,true)`, [target]);
    const result = await worker(binaries.synthetic, "assign", oid);
    check(result.outcome === "failed" && result.secretFrames === 0, table + "_active_gate_denied");
    await fixture.control.query(`DELETE FROM private.${table}`);
  }
  for (const [table, columns, values] of [
    ["square_account_configuration", "broker_login,surface_enabled,blocked", "$1,NULL,false"],
    ["square_remote_sandbox_binding", "broker_login,enabled", "$1,NULL"],
    ["square_gcp_callback_binding", "broker_login,enabled", "$1,NULL"]
  ]) {
    await fixture.control.query(`INSERT INTO private.${table}(${columns}) VALUES(${values})`, [target]);
    const unknown = await worker(binaries.synthetic, "assign", oid);
    check(unknown.outcome === "failed" && unknown.secretFrames === 0 && unknown.ready === 0, table + "_unknown_gate_denied_before_generation");
    await fixture.control.query(`DELETE FROM private.${table}`);
  }
  await fixture.control.query(`GRANT ${capability} TO synthetic_other_grantor WITH ADMIN TRUE`);
  const otherGrantor = await fixture.connect("synthetic_other_grantor");
  await otherGrantor.query(`GRANT ${capability} TO ${target} WITH ADMIN TRUE`);
  const grantCount = (await fixture.control.query("SELECT count(*)::int AS n FROM pg_auth_members WHERE roleid=(SELECT oid FROM pg_roles WHERE rolname=$1) AND member=$2::oid", [capability, oid])).rows[0].n;
  check(grantCount === 2, "actual_pg17_second_grantor_membership_created");
  const expandedGrant = await worker(binaries.synthetic, "assign", oid);
  check(expandedGrant.outcome === "failed" && expandedGrant.secretFrames === 0 && expandedGrant.ready === 0, "secondary_admin_grant_denied_despite_one_compliant_membership");
  await otherGrantor.query(`REVOKE ${capability} FROM ${target}`); await otherGrantor.end();
  await fixture.control.query(`REVOKE ${capability} FROM synthetic_other_grantor`);
  check((await worker(binaries.synthetic, "inspect", oid)).outcome === "inspected", "secondary_grant_removal_preserves_original_valid_membership");
  stage = "lock_timeout";
  const locker = await fixture.connect();
  await locker.query("BEGIN; LOCK TABLE private.square_gcp_callback_binding IN ACCESS EXCLUSIVE MODE");
  offsets = fixture.logOffsets(); const locked = await worker(binaries.synthetic, "assign", oid);
  check(locked.outcome === "failed" && locked.secretFrames === 0 && locked.elapsed < 6000, "actual_lock_timeout_before_generation");
  await locker.query("ROLLBACK"); await locker.end(); await privacy(offsets, "lock_timeout");
  const tupleLocker = await fixture.connect();
  await tupleLocker.query(`BEGIN; ALTER ROLE ${target} NOLOGIN`);
  offsets = fixture.logOffsets(); const tupleBlocked = await worker(binaries.synthetic, "assign", oid);
  check(tupleBlocked.outcome === "failed" && tupleBlocked.secretFrames === 0 && tupleBlocked.ready === 0 && tupleBlocked.elapsed < 6000,
    "actual_target_tuple_lock_timeout_before_generation");
  await tupleLocker.query("ROLLBACK"); await tupleLocker.end(); await privacy(offsets, "target_tuple_timeout");
  stage = "assignment";
  offsets = fixture.logOffsets(); let result = await worker(binaries.synthetic, "assign", oid, { onCandidate: async (_password, child) => {
    // Fresh autocommit snapshot while the candidate's password ALTER has already
    // completed and the private store acknowledgement is still withheld.
    const rows = (await fixture.control.query("SELECT state,query FROM pg_stat_activity WHERE application_name='vaeroex-native-provisioner' AND usename=$1", [admin])).rows;
    check(rows.length === 1 && rows[0].state === "disabled" && rows[0].query === "", "protected_candidate_activity_is_disabled_and_empty");
    if (process.platform === "linux") {
      const status = fs.readFileSync(`/proc/${child.pid}/status`, "utf8");
      const locked = /^VmLck:\s+(\d+)\s+kB$/m.exec(status);
      check(locked !== null && Number(locked[1]) > 0, "linux_candidate_pages_remain_locked_during_private_store_wait");
      linuxMlockMeasured = true;
    }
  } });
  check(result.outcome === "assigned" && result.secretFrames === 1, "native_assignment_and_private_store_ack");
  const firstPassword = result.password;
  current = await role(); check(!current.rolcanlogin && current.rolpassword.startsWith("SCRAM-SHA-256$"), "assigned_catalog_verifier_only_and_still_nologin");
  let logs = await privacy(offsets, "assigned");
  check(logs.includes(Buffer.from("AUDIT:")) && logs.includes(Buffer.from(target)) && logs.includes(Buffer.from("<REDACTED>")), "payload_free_role_audit_positive_control");
  stage = "activate_and_fence";
  check((await worker(binaries.synthetic, "activate", oid)).outcome === "activated", "separate_local_activation");
  check((await worker(binaries.synthetic, "authenticate", oid, { host: "127.0.0.1", password: firstPassword })).outcome === "authenticated", "native_private_credential_authentication");
  const session = await fixture.connect(target, firstPassword, "tls");
  check((await session.query("SELECT session_user AS value")).rows[0].value === target, "actual_scram_tls_broker_login");
  check((await worker(binaries.synthetic, "fence", oid)).outcome === "fenced", "separate_fence_operation");
  await deadline(async () => (await fixture.control.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE usename=$1", [target])).rows[0].n === 0);
  check(!(await role()).rolcanlogin, "fence_nologin_and_terminates_existing_session");
  stage = "cancel_and_store_timeout";
  for (const [name, options] of [["cancel_after_candidate", { cancelCandidate: true }], ["store_ack_timeout", { withholdAck: true }]]) {
    const before = (await role()).rolpassword; offsets = fixture.logOffsets();
    result = await worker(binaries.synthetic, "assign", oid, options);
    check(result.outcome === "uncertain" && result.secretFrames === 1, name + "_fixed_uncertain");
    check((await role()).rolpassword === before && !(await role()).rolcanlogin, name + "_rollback_keeps_fence");
    await privacy(offsets, name);
  }
  stage = "lost_commit_ack";
  const relay = await proxy();
  try {
    const before = (await role()).rolpassword; offsets = fixture.logOffsets();
    result = await worker(binaries.synthetic, "assign", oid, { host: "127.0.0.1", port: relay.port, onCandidate: () => relay.suppressReplies() });
    check(result.outcome === "uncertain" && result.secretFrames === 1, "lost_database_ack_reports_uncertain_without_retry");
    check((await role()).rolpassword !== before && !(await role()).rolcanlogin, "lost_ack_actual_commit_observed_independently_with_gate_closed");
    await privacy(offsets, "lost_ack");
  } finally { await relay.close(); }
  stage = "rotation_recovery";
  offsets = fixture.logOffsets(); result = await worker(binaries.synthetic, "assign", oid);
  check(result.outcome === "assigned" && result.password !== firstPassword, "new_explicit_rotation_after_uncertainty");
  check((await worker(binaries.synthetic, "activate", oid)).outcome === "activated", "separate_recovery_activation");
  const recovered = await fixture.connect(target, result.password, "tls");
  check((await recovered.query("SELECT session_user AS value")).rows[0].value === target, "rotated_credential_actual_authentication");
  let oldDenied = false; try { await fixture.connect(target, firstPassword, "tls"); } catch { oldDenied = true; }
  check(oldDenied, "previous_credential_cannot_authenticate_after_rotation");
  check((await worker(binaries.synthetic, "fence", oid)).outcome === "fenced", "final_target_closed");
  await privacy(offsets, "rotation");
  const fresh = await fixture.connect();
  check((await fresh.query("SHOW log_statement")).rows[0].log_statement === "ddl", "new_connection_has_original_log_controls");
  check((await fresh.query("SHOW track_activities")).rows[0].track_activities === "on", "new_connection_has_original_activity_controls");
  await fresh.end();
  stage = "integrated_coordinator";
  const { createSyntheticProvisioningCoordinator, createInMemorySyntheticSecretStore } = await import("../lifecycle.mjs");
  const { createLocalSyntheticNativeAdapter } = await import("../adapter.mjs");
  const integratedRole = "square_sandbox_integrated_broker";
  const nativeTarget = Object.freeze({ projectReference: "synthetic-local", host: "127.0.0.1", port: fixture.port, database: "postgres",
    role: integratedRole, systemIdentifier: fixture.systemId, databaseOid: fixture.databaseOid, adminRole: admin,
    capabilityRole: capability, rootCertificate: fixture.cert, roleOid: "0" });
  const native = createLocalSyntheticNativeAdapter({ executable: binaries.synthetic, target: nativeTarget });
  const store = createInMemorySyntheticSecretStore(), events = [];
  const coordinator = createSyntheticProvisioningCoordinator({ target: nativeTarget, native,
    secretStore: { ...store, async stage(handle, bytes) { secrets.push(bytes.toString("ascii")); return store.stage(handle, bytes); } },
    audit: { async append(event) { events.push(event); return { ack: true }; } } });
  offsets = fixture.logOffsets();
  for (const operation of ["create", "rotate"]) {
    const coordinated = await coordinator.run({ operation, actor: "synthetic-operator", intent: "integrated-" + operation,
      approvalId: "synthetic-only", deadlineMs: 30000 });
    check(coordinated.outcome === "staged_ready" && coordinated.credentialPublished === false &&
      coordinated.applicationAuthority === "verified_closed", "integrated_" + operation + "_native_staged_ready_never_published");
  }
  check(events.some(event => event.phase === "authenticate_candidate" && event.outcome === "acknowledged"), "integrated_actual_native_authentication_audit");
  check(events.every(event => Object.keys(event).sort().join(",") === "actor,intent,operation,outcome,phase,targetRole,time"), "integrated_audit_metadata_allowlist");
  await privacy(offsets, "integrated_coordinator");
  const integratedOid = (await fixture.control.query("SELECT oid::text FROM pg_roles WHERE rolname=$1", [integratedRole])).rows[0].oid;
  const finalFence = await native.fence({ target: Object.freeze({ ...nativeTarget, roleOid: integratedOid }), intent: "integrated-final-fence",
    approvalId: "synthetic-only", signal: new AbortController().signal });
  check(finalFence.ack && finalFence.noLogin && finalFence.sessionsTerminated, "integrated_fixture_closed_after_proof");
  await fixture.stop();
  check(!fixture.statBytes().includes(Buffer.from("SCRAM-SHA-256$")) && secrets.every(value => !fixture.statBytes().includes(Buffer.from(value))),
    "protected_saved_statistics_before_operator_fixture");
  stage = "actual_non_superuser_operator";
  // New pristine fixture, explicitly broader synthetic-only GUC permissions.
  // The preceding matching-hosted-permission negative remains unchanged.
  fixture = await createFixture({ expandedOperator: true });
  const lane = await fixture.connect("synthetic_lane_admin");
  check(!(await lane.query("SELECT rolsuper FROM pg_roles WHERE rolname=session_user")).rows[0].rolsuper, "actual_lane_operator_is_not_superuser");
  check(!(await lane.query("SELECT has_parameter_privilege(current_user,'track_activities','SET') AS allowed")).rows[0].allowed,
    "same_non_superuser_operator_native_acl_false");
  await lane.query("SET track_activities=off");
  check((await lane.query("SHOW track_activities")).rows[0].track_activities === "off", "same_non_superuser_actual_supautils_set_success");
  await lane.end();
  offsets = fixture.logOffsets();
  check((await worker(binaries.synthetic, "prepare", 0, { admin: "synthetic_lane_admin" })).outcome === "prepared",
    "non_superuser_createrole_prepares_actual_target");
  const laneOid = (await role()).oid;
  const membership = (await fixture.control.query("SELECT m.admin_option,m.inherit_option,m.set_option FROM pg_auth_members m JOIN pg_roles member_role ON member_role.oid=m.member WHERE m.roleid=$1::oid AND member_role.rolname='synthetic_lane_admin'", [laneOid])).rows;
  check(membership.length === 1 && membership[0].admin_option && !membership[0].inherit_option && !membership[0].set_option,
    "postgres_17_creator_membership_is_admin_only");
  const laneAssigned = await worker(binaries.synthetic, "assign", laneOid, { admin: "synthetic_lane_admin" });
  check(laneAssigned.outcome === "assigned" && laneAssigned.secretFrames === 1, "non_superuser_operator_assigns_without_extra_target_privileges");
  check((await worker(binaries.synthetic, "activate", laneOid, { admin: "synthetic_lane_admin" })).outcome === "activated", "non_superuser_operator_activates_separately");
  check((await worker(binaries.synthetic, "authenticate", laneOid, { admin: "synthetic_lane_admin", host: "127.0.0.1", password: laneAssigned.password })).outcome === "authenticated", "non_superuser_operator_native_scram_authentication");
  const laneSession = await fixture.connect(target, laneAssigned.password, "tls");
  await laneSession.query("SELECT 1");
  check((await worker(binaries.synthetic, "fence", laneOid, { admin: "synthetic_lane_admin" })).outcome === "fenced", "non_superuser_operator_fences_and_terminates_existing_session");
  await deadline(async () => (await fixture.control.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE usename=$1", [target])).rows[0].n === 0);
  check(!(await role()).rolcanlogin, "non_superuser_fixture_final_target_nologin");
  await privacy(offsets, "non_superuser_operator");
  return binaries;
}
(async () => {
  let binaries;
  try { binaries = await main(); } catch (error) { failure = error.safeStage ?? stage; }
  finally { if (fixture) try { await fixture.stop(); } catch { failure = "local_cluster_stop"; } }
  if (fixture && !failure) try {
    const saved = fixture.statBytes();
    check(!saved.includes(Buffer.from("SCRAM-SHA-256$")) && secrets.every(value => !saved.includes(Buffer.from(value))), "stopped_pgstat_saved_file_has_no_payload");
  } catch { failure = "stopped_pgstat_saved_file_has_no_payload"; }
  const report = { localOnly: true, hostedQualification: false, externalMutations: 0, assertions: passed.length, passed,
    platform: process.platform, linuxMlockMeasured,
    dependencies: fixture?.versions ?? null, nativeSourceSha256: binaries?.sourceSha256 ?? null, failure: failure ?? null,
    stopped: fixture ? !fs.existsSync(path.join(fixture.data, "postmaster.pid")) : true };
  if (fixture) fs.writeFileSync(path.join(fixture.root, "qualification-report.json"), JSON.stringify(report, null, 2) + "\n", { mode: 0o600 });
  process.stdout.write(JSON.stringify({ suite: "native_broker_local_synthetic", assertions: report.assertions, failure: report.failure,
    stopped: report.stopped, localOnly: true, hostedQualification: false }) + "\n");
  process.exitCode = failure ? 1 : 0;
})();
