import Link from "next/link";
import type { Route } from "next";
import { generateReportAction } from "@/app/app/reports/actions";
import { ContextualAskVaeroex } from "@/components/ai/ContextualAskVaeroex";
import { GlobalSearchTrigger } from "@/components/app/GlobalSearchTrigger";
import { PageHeader } from "@/components/operations/PageHeader";
import { StatusBadge } from "@/components/operations/StatusBadge";
import { filterBusinessEvidence } from "@/lib/intelligence/evidence-eligibility";
import type { Database, Json } from "@/lib/supabase/types";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

export const dynamic = "force-dynamic";

type ReportRow = Database["public"]["Tables"]["reports"]["Row"];
type JsonRecord = Record<string, unknown>;

const BRIEFING_PERIODS = ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly", "Year to Date"];
const BRIEFING_TYPES = ["Executive Summary", "Intelligence Summary", "Accountability Review", "Bottleneck Review", "Readiness Snapshot"];

function todayDate() {
  return new Date().toISOString().slice(0, 10);
}

function isRecord(value: unknown): value is JsonRecord {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function asRecord(value: Json | unknown): JsonRecord {
  return isRecord(value) ? value : {};
}

function str(value: unknown, fallback = "") {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString();
}

function briefingDateLabel(report: ReportRow) {
  if (report.date_range_start && report.date_range_end) {
    return `${report.date_range_start} to ${report.date_range_end}`;
  }

  return formatDate(report.created_at);
}

function sourceDataSummary(report: ReportRow) {
  const source = asRecord(report.source_data_json);
  const current = asRecord(source.current);
  const counts = asRecord(current.counts);
  const labels = [
    typeof counts.kpis === "number" ? `${counts.kpis} KPI signal${counts.kpis === 1 ? "" : "s"}` : "",
    typeof counts.tasks === "number" ? `${counts.tasks} Business Signal${counts.tasks === 1 ? "" : "s"}` : "",
    typeof counts.issues === "number" ? `${counts.issues} issue${counts.issues === 1 ? "" : "s"}` : "",
    typeof counts.files === "number" ? `${counts.files} source file${counts.files === 1 ? "" : "s"}` : "",
    str(source.category)
  ].filter(Boolean);

  return labels.length ? labels.join(" · ") : "Workspace context";
}

function summaryFromBody(body: string | null) {
  const lines = (body || "")
    .split("\n")
    .map((line) => line.replace(/^#+\s*/, "").replace(/^-\s*/, "").trim())
    .filter(Boolean)
    .filter((line) => !/^Executive Summary$/i.test(line));

  return lines.slice(0, 2).join(" ") || "Saved Vaeroex briefing. Open the full record for the complete summary, evidence, and recommendations.";
}

function confidenceForReport(report: ReportRow) {
  const source = asRecord(report.source_data_json);
  const current = asRecord(source.current);
  const counts = asRecord(current.counts);
  const signalCount = ["kpis", "tasks", "issues", "files", "reports", "crm"]
    .map((key) => counts[key])
    .filter((value): value is number => typeof value === "number")
    .reduce((total, value) => total + value, 0);

  if (signalCount >= 10) return "High";
  if (signalCount >= 3) return "Medium";
  return "Developing";
}

function confidenceClass(value: string) {
  if (value === "High") return "border-cyan-300/40 bg-cyan-400/15 text-cyan-100";
  if (value === "Medium") return "border-blue-300/30 bg-blue-500/15 text-blue-100";
  return "border-slate-400/30 bg-slate-500/15 text-slate-100";
}

export default async function BriefingsPage() {
  const { supabase, workspaceId, context } = await requireWorkspacePage();
  const { data, error } = await supabase
    .from("reports")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false })
    .limit(24);
  const reports = filterBusinessEvidence((data || []) as ReportRow[]);
  const latestBriefing = reports[0];

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Briefings"
        title="Saved Intelligence Briefings"
        description="Concise summaries generated by Vaeroex. Briefings preserve the answer first, with evidence and source records available when you need them."
        actions={
          <GlobalSearchTrigger initialQuery="Create a briefing from current workspace evidence" className="rounded-lg bg-vaeroex-blue px-4 py-2 text-sm font-semibold text-white hover:bg-blue-950/70 hover:ring-1 hover:ring-vaeroex-accent/45">
            Search or Ask
          </GlobalSearchTrigger>
        }
      />

      {error ? (
        <div className="rounded-lg border border-red-400/35 bg-red-950/30 p-3 text-sm text-red-100">
          {error.message || "Briefings could not be loaded."}
        </div>
      ) : null}

      <section className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]">
        <div className="rounded-lg border border-white/10 bg-[#08111f] p-5 text-slate-100 shadow-panel">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-vaeroex-accent">Generate briefing</p>
          <h2 className="mt-3 text-xl font-semibold text-white">Create a saved leadership summary.</h2>
          <p className="mt-2 text-sm leading-6 text-slate-300">
            Choose a period and Vaeroex will summarize risks, opportunities, recommendations, and evidence from the active workspace.
          </p>
          <form action={generateReportAction} className="mt-5 grid gap-3">
            <input type="hidden" name="return_path" value="/app/briefings" />
            <label className="grid gap-1 text-sm font-semibold text-slate-100">
              Period
              <select name="report_period" defaultValue="Weekly" className="min-h-11 rounded-lg border border-white/10 bg-slate-950/80 px-3 py-2 text-sm text-white">
                {BRIEFING_PERIODS.map((period) => (
                  <option key={period} value={period}>{period}</option>
                ))}
              </select>
            </label>
            <label className="grid gap-1 text-sm font-semibold text-slate-100">
              Date in period
              <input name="anchor_date" type="date" defaultValue={todayDate()} className="min-h-11 rounded-lg border border-white/10 bg-slate-950/80 px-3 py-2 text-sm text-white" />
            </label>
            <label className="grid gap-1 text-sm font-semibold text-slate-100">
              Briefing type
              <select name="report_type" defaultValue="Executive Summary" className="min-h-11 rounded-lg border border-white/10 bg-slate-950/80 px-3 py-2 text-sm text-white">
                {BRIEFING_TYPES.map((type) => (
                  <option key={type} value={type}>{type}</option>
                ))}
              </select>
            </label>
            <input type="hidden" name="category" value="All" />
            <button className="min-h-11 rounded-lg bg-vaeroex-blue px-4 py-2 text-sm font-semibold text-white">
              Generate Briefing
            </button>
          </form>
        </div>

        <div className="rounded-lg border border-white/10 bg-[#08111f] p-5 text-slate-100 shadow-panel">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Latest briefing</p>
              <h2 className="mt-3 text-2xl font-semibold text-white">{latestBriefing?.title || "No saved briefing yet"}</h2>
            </div>
            <StatusBadge value={`${reports.length} saved`} />
          </div>
          <p className="mt-3 text-sm leading-6 text-slate-300">
            {latestBriefing
              ? summaryFromBody(latestBriefing.body_markdown)
              : "Generate a briefing after adding business context, uploading source material, importing KPIs, or asking Vaeroex a question."}
          </p>
          <div className="mt-5 flex flex-wrap gap-2">
            <Link href="/app/sources" className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-sm font-semibold text-slate-100 hover:bg-cyan-950/30">
              View Evidence
            </Link>
            <Link href="/app/intelligence" className="rounded-lg border border-cyan-300/25 bg-cyan-400/10 px-3 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20">
              View Intelligence
            </Link>
            <Link href="/app/reports" className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-sm font-semibold text-slate-100 hover:bg-cyan-950/30">
              Advanced records
            </Link>
          </div>
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-center justify-between gap-3">
          <h2 className="text-base font-semibold text-slate-100">Saved briefings</h2>
          <StatusBadge value="Answer first" />
        </div>
        {reports.length ? (
          <div className="grid gap-3 xl:grid-cols-2">
            {reports.map((report) => {
              const confidence = confidenceForReport(report);

              return (
                <article key={report.id} className="rounded-lg border border-white/10 bg-[#08111f] p-4 text-slate-100 shadow-panel">
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">{report.report_type}</p>
                      <h3 className="mt-2 text-base font-semibold text-white">{report.title}</h3>
                      <p className="mt-1 text-xs text-slate-500">{briefingDateLabel(report)}</p>
                    </div>
                    <span className={`w-fit rounded-full border px-2.5 py-1 text-xs font-semibold ${confidenceClass(confidence)}`}>
                      {confidence} confidence
                    </span>
                  </div>
                  <p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-300">{summaryFromBody(report.body_markdown)}</p>
                  <details className="mt-4 rounded-lg border border-white/10 bg-white/[0.04] p-3">
                    <summary className="cursor-pointer text-xs font-semibold text-cyan-100">Evidence summary</summary>
                    <p className="mt-3 text-xs leading-5 text-slate-300">{sourceDataSummary(report)}</p>
                  </details>
                  <div className="mt-4 flex flex-wrap gap-2">
                    <Link href={`/app/reports?q=${encodeURIComponent(report.title)}` as Route} className="rounded-lg bg-vaeroex-blue px-3 py-2 text-xs font-semibold text-white">
                      View briefing
                    </Link>
                    <ContextualAskVaeroex
                      label="Explain This"
                      prompt={`Explain the key point in this briefing, why it matters, which briefing evidence supports it, and what remains uncertain: ${report.title}`}
                      contextType="briefing"
                      contextId={report.id}
                      sourceTitle={report.title}
                      sourceSummary={summaryFromBody(report.body_markdown)}
                      evidence={[
                        `Report type: ${report.report_type}`,
                        `Date range: ${briefingDateLabel(report)}`,
                        `Source data: ${sourceDataSummary(report)}`,
                        `Confidence: ${confidence}`
                      ]}
                      compact
                    />
                  </div>
                </article>
              );
            })}
          </div>
        ) : (
          <div className="rounded-lg border border-white/10 bg-[#08111f] p-5 text-sm leading-6 text-slate-300">
            No briefings have been saved yet. Upload source material or ask Vaeroex what leadership should know, then generate the first briefing.
          </div>
        )}
      </section>
    </div>
  );
}
