import type { Database, Json } from "@/lib/supabase/types";

export type ReportRow = Database["public"]["Tables"]["reports"]["Row"];
export type NormalizedReportType =
  | "executive_brief"
  | "board_report"
  | "improvement_plan"
  | "investigation_summary";
export type ReportPresentationType = NormalizedReportType | "source_review" | "supporting_document";

export const REPORT_FILTERS: Array<{ value: "all" | NormalizedReportType; label: string }> = [
  { value: "all", label: "All" },
  { value: "executive_brief", label: "Executive Briefs" },
  { value: "board_report", label: "Board Reports" },
  { value: "improvement_plan", label: "Improvement Plans" },
  { value: "investigation_summary", label: "Investigation Summaries" }
];

const REPORT_LABELS: Record<ReportPresentationType, string> = {
  executive_brief: "Executive Brief",
  board_report: "Board Report",
  improvement_plan: "Improvement Plan",
  investigation_summary: "Investigation Summary",
  source_review: "Source Review",
  supporting_document: "Supporting Document"
};

type JsonRecord = Record<string, unknown>;

function asRecord(value: Json | unknown): JsonRecord {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as JsonRecord) : {};
}

function str(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

export function normalizedReportType(report: Pick<ReportRow, "report_type" | "title" | "source_data_json">): ReportPresentationType {
  const source = asRecord(report.source_data_json);
  const value = `${report.report_type} ${report.title} ${str(source.output_type)} ${str(source.report_type)} ${str(source.generated_from)}`.toLowerCase();

  if (/file\s*(review|analysis)|source\s*review/.test(value)) return "source_review";
  if (/checklist|sop\s*draft|meeting\s*(agenda|brief)/.test(value)) return "supporting_document";
  if (/board|business\s*review\s*package|quarterly\s*business\s*review/.test(value)) return "board_report";
  if (/improvement|action\s*plan|operational\s*plan/.test(value)) return "improvement_plan";
  if (/investigation|bottleneck|accountability|risk\s*brief|root\s*cause|anomaly/.test(value)) return "investigation_summary";
  return "executive_brief";
}

export function reportTypeLabel(type: ReportPresentationType) {
  return REPORT_LABELS[type];
}

export function isPrimaryReportType(type: ReportPresentationType): type is NormalizedReportType {
  return type !== "source_review" && type !== "supporting_document";
}

export function reportDisplayTitle(report: Pick<ReportRow, "report_type" | "title" | "source_data_json">) {
  const type = normalizedReportType(report);
  const cleaned = report.title
    .replace(/\s*[-–—]\s*Generated by Vaeroex\s*$/i, "")
    .replace(/^Vaeroex\s+/i, "")
    .trim();
  const generic = /^(daily|weekly|monthly|quarterly|yearly|year to date)?\s*(intelligence|executive|operations|operational|readiness|accountability|bottleneck)?\s*(summary|review|report|snapshot|briefing)?$/i.test(cleaned);

  return generic || !cleaned ? reportTypeLabel(type) : cleaned;
}

export function reportPeriodLabel(report: Pick<ReportRow, "date_range_start" | "date_range_end" | "created_at">) {
  if (report.date_range_start && report.date_range_end) {
    const start = new Date(`${report.date_range_start}T12:00:00.000Z`);
    const end = new Date(`${report.date_range_end}T12:00:00.000Z`);
    const formatter = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" });
    return report.date_range_start === report.date_range_end ? formatter.format(start) : `${formatter.format(start)} – ${formatter.format(end)}`;
  }

  return `Generated ${new Date(report.created_at).toLocaleDateString()}`;
}

function cleanMarkdownLine(line: string) {
  return line.replace(/^#{1,6}\s*/, "").replace(/^[-*]\s*/, "").replace(/\*\*/g, "").trim();
}

export function reportSummary(body: string | null, fallback = "Open the report to review its findings, evidence, and limitations.") {
  const lines = (body || "")
    .split("\n")
    .map(cleanMarkdownLine)
    .filter(Boolean)
    .filter((line) => !/^(executive summary|report details|evidence|supporting evidence)$/i.test(line));
  const summary = lines.slice(0, 2).join(" ");
  if (!summary) return fallback;
  return summary.length > 220 ? `${summary.slice(0, 220).replace(/\s+\S*$/, "").trim()}...` : summary;
}

export type ReportEvidenceReadiness = "Good" | "Limited" | "Unverified";

export function reportEvidenceReadiness(report: Pick<ReportRow, "source_data_json">): ReportEvidenceReadiness {
  const source = asRecord(report.source_data_json);
  const evidenceCount = Number(source.evidence_count || asRecord(source.evidence).source_count || 0);
  const current = asRecord(source.current);
  const currentEvidence = asRecord(current.evidence);
  const currentCount = Number(currentEvidence.original_source_count || 0);
  const count = Math.max(evidenceCount, currentCount);

  if (count >= 3) return "Good";
  if (count >= 1 || Array.isArray(source.evidence)) return "Limited";
  return "Unverified";
}

export type ReportSection = { title: string; lines: string[] };

export function parseReportSections(body: string | null): ReportSection[] {
  const sections: ReportSection[] = [];
  let current: ReportSection | null = null;

  for (const rawLine of (body || "").split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("# ")) continue;
    if (line.startsWith("## ")) {
      current = { title: line.replace(/^##\s*/, ""), lines: [] };
      sections.push(current);
      continue;
    }
    if (!current) {
      current = { title: "Executive answer", lines: [] };
      sections.push(current);
    }
    current.lines.push(line);
  }

  return sections.length ? sections : [{ title: "Executive answer", lines: ["No report content is available."] }];
}

export function reportSourceCount(report: Pick<ReportRow, "source_data_json">) {
  const source = asRecord(report.source_data_json);
  const current = asRecord(source.current);
  const evidence = asRecord(current.evidence);
  return Number(evidence.original_source_count || source.evidence_count || 0);
}
