import { createTaskAction, updateTaskStatusAction } from "@/app/app/operations/actions";
import { EmptyState } from "@/components/operations/EmptyState";
import { ErrorNotice } from "@/components/operations/ErrorNotice";
import { PrimaryButton, SelectInput, TextArea, TextInput } from "@/components/operations/FormControls";
import { PageHeader } from "@/components/operations/PageHeader";
import { SectionCard } from "@/components/operations/SectionCard";
import { StatusBadge } from "@/components/operations/StatusBadge";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

type TasksPageProps = {
  searchParams?: Promise<{ error?: string }>;
};

const taskStatuses = ["To Do", "In Progress", "Waiting", "Done"];
const priorities = ["Low", "Medium", "High", "Urgent"];

export default async function TasksPage({ searchParams }: TasksPageProps) {
  const params = await searchParams;
  const { supabase, workspaceId } = await requireWorkspacePage();
  const { data: tasks, error } = await supabase
    .from("tasks")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });

  const openTasks = (tasks || []).filter((task) => task.status !== "Done");
  const doneTasks = (tasks || []).filter((task) => task.status === "Done");

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Tasks"
        title="Follow-up accountability"
        description="Track work from manual entry, form submissions, issue logs, setup plans, and Vaeroex-reviewed recommendations."
      />

      <ErrorNotice message={params?.error || error?.message} />

      <section className="grid gap-4 md:grid-cols-3">
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Open</p>
          <p className="mt-2 text-3xl font-semibold">{openTasks.length}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Done</p>
          <p className="mt-2 text-3xl font-semibold">{doneTasks.length}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Urgent or high</p>
          <p className="mt-2 text-3xl font-semibold">{(tasks || []).filter((task) => ["Urgent", "High"].includes(task.priority)).length}</p>
        </article>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1fr_380px]">
        <SectionCard title="Task board" description="All task data is scoped to the current workspace.">
          {tasks?.length ? (
            <div className="space-y-4">
              {tasks.map((task) => (
                <article key={task.id} className="rounded-lg border border-line p-4">
                  <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                    <div>
                      <p className="font-semibold">{task.title}</p>
                      <p className="mt-1 text-sm leading-6 text-muted">{task.description || "No description."}</p>
                      <p className="mt-2 text-xs text-muted">
                        {task.category || "General"} · Due {task.due_date || "not set"}
                        {task.ai_generated ? " · Generated by Vaeroex" : ""}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <StatusBadge value={task.priority} />
                      <StatusBadge value={task.status} />
                    </div>
                  </div>
                  <form action={updateTaskStatusAction} className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end">
                    <input type="hidden" name="task_id" value={task.id} />
                    <SelectInput label="Update status" name="status" defaultValue={task.status} options={taskStatuses} />
                    <PrimaryButton>Save status</PrimaryButton>
                  </form>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState title="No tasks yet" description="Create a task manually or convert a submission or issue into follow-up work." />
          )}
        </SectionCard>

        <SectionCard title="Create task" description="Use tasks for the next concrete action, not long notes.">
          <form action={createTaskAction} className="space-y-4">
            <TextInput label="Task title" name="title" required />
            <TextArea label="Description" name="description" rows={4} />
            <SelectInput label="Status" name="status" defaultValue="To Do" options={taskStatuses} />
            <SelectInput label="Priority" name="priority" defaultValue="Medium" options={priorities} />
            <TextInput label="Category" name="category" placeholder="Follow-up, safety, onboarding, customer" />
            <TextInput label="Due date" name="due_date" type="date" />
            <PrimaryButton>Create task</PrimaryButton>
          </form>
        </SectionCard>
      </section>
    </div>
  );
}
