import { createTaskAction } from "@/app/app/operations/actions";
import { ErrorNotice } from "@/components/operations/ErrorNotice";
import { PrimaryButton, SelectInput, TextArea, TextInput } from "@/components/operations/FormControls";
import { ManagedRecordList, type ManagedRecordEditField } from "@/components/operations/ManagedRecordList";
import { PageHeader } from "@/components/operations/PageHeader";
import { SectionCard } from "@/components/operations/SectionCard";
import { getRecordFolders, managedValues, shortPreview } from "@/lib/records/management";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

type TasksPageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

const taskStatuses = ["To Do", "In Progress", "Waiting", "Done"];
const priorities = ["Low", "Medium", "High", "Urgent"];
const taskEditFields: ManagedRecordEditField[] = [
  { name: "title", label: "Task title", required: true },
  { name: "description", label: "Description", type: "textarea", rows: 4 },
  { name: "status", label: "Status", type: "select", options: taskStatuses },
  { name: "priority", label: "Priority", type: "select", options: priorities },
  { name: "category", label: "Category" },
  { name: "due_date", label: "Due date", type: "date" }
];

export default async function TasksPage({ searchParams }: TasksPageProps) {
  const params = await searchParams;
  const { supabase, workspaceId } = await requireWorkspacePage();
  const [{ data: tasks, error }, folderResult] = await Promise.all([
    supabase
      .from("tasks")
      .select("*")
      .eq("workspace_id", workspaceId)
      .order("created_at", { ascending: false }),
    getRecordFolders(supabase, workspaceId, "tasks")
  ]);

  const openTasks = (tasks || []).filter((task) => task.status !== "Done");
  const doneTasks = (tasks || []).filter((task) => task.status === "Done");
  const managedTasks = (tasks || []).map((task) => {
    const management = managedValues(task);

    return {
      id: task.id,
      title: task.title,
      type: task.ai_generated ? "Vaeroex task" : "Task",
      status: task.status,
      owner: task.assigned_to ? "Assigned" : "Unassigned",
      category: task.category || "General",
      createdAt: task.created_at,
      updatedAt: management.updatedAt || task.updated_at,
      folderId: management.folderId,
      archivedAt: management.archivedAt,
      deletedAt: management.deletedAt,
      preview: shortPreview(task.description, "No description."),
      meta: [
        { label: "Priority", value: task.priority },
        { label: "Due date", value: task.due_date || "Not set" },
        { label: "Source", value: task.ai_generated ? "Generated by Vaeroex" : task.related_type || "Manual" }
      ],
      editFields: taskEditFields,
      editValues: {
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        category: task.category,
        due_date: task.due_date
      },
      children: <p className="text-sm leading-6 text-muted">{task.description || "No description."}</p>
    };
  });

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Tasks"
        title="Tasks"
        description="Track work from manual entry, form submissions, issue logs, setup plans, and Vaeroex-reviewed recommendations."
      />

      <ErrorNotice message={(params?.error as string | undefined) || error?.message || folderResult.error?.message} />

      <section className="grid gap-4 md:grid-cols-3">
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Open</p>
          <p className="mt-2 text-3xl font-semibold">{openTasks.length}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Done</p>
          <p className="mt-2 text-3xl font-semibold">{doneTasks.length}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Urgent or high</p>
          <p className="mt-2 text-3xl font-semibold">{(tasks || []).filter((task) => ["Urgent", "High"].includes(task.priority)).length}</p>
        </article>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1fr_380px]">
        <SectionCard title="Task board" description="All task data is scoped to the current workspace.">
          <ManagedRecordList
            collection="tasks"
            records={managedTasks}
            folders={folderResult.folders}
            title="Task records"
            description="Search, group, edit, archive, duplicate, or bulk-manage follow-up work."
            emptyTitle="No tasks yet"
            emptyDescription="Create a task manually or convert a submission or issue into follow-up work."
            searchParams={params}
          />
        </SectionCard>

        <SectionCard title="Create task" description="Use tasks for the next concrete action, not long notes.">
          <form action={createTaskAction} className="space-y-4">
            <TextInput label="Task title" name="title" required />
            <TextArea label="Description" name="description" rows={4} />
            <SelectInput label="Status" name="status" defaultValue="To Do" options={taskStatuses} />
            <SelectInput label="Priority" name="priority" defaultValue="Medium" options={priorities} />
            <TextInput label="Category" name="category" placeholder="Follow-up, safety, onboarding, customer" />
            <TextInput label="Due date" name="due_date" type="date" />
            <PrimaryButton>Create task</PrimaryButton>
          </form>
        </SectionCard>
      </section>
    </div>
  );
}
