import { createReportAction } from "@/app/app/operations/actions";
import { EmptyState } from "@/components/operations/EmptyState";
import { ErrorNotice } from "@/components/operations/ErrorNotice";
import { PrimaryButton, SelectInput, TextArea, TextInput } from "@/components/operations/FormControls";
import { JsonPreview } from "@/components/operations/JsonPreview";
import { PageHeader } from "@/components/operations/PageHeader";
import { SectionCard } from "@/components/operations/SectionCard";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

type ReportsPageProps = {
  searchParams?: Promise<{ error?: string }>;
};

export default async function ReportsPage({ searchParams }: ReportsPageProps) {
  const params = await searchParams;
  const { supabase, workspaceId } = await requireWorkspacePage();
  const [{ data: reports, error }, taskCount, issueCount, submissionCount, assetCount] = await Promise.all([
    supabase
      .from("reports")
      .select("*")
      .eq("workspace_id", workspaceId)
      .order("created_at", { ascending: false }),
    supabase.from("tasks").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId).neq("status", "Done"),
    supabase.from("issues").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId).neq("status", "Closed"),
    supabase.from("form_submissions").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId),
    supabase.from("assets").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId).neq("status", "Ready")
  ]);

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Operations reports"
        description="Create weekly summaries, bottleneck reviews, and operational snapshots. Reports generated with the product voice are labeled Generated by Vaeroex."
      />

      <ErrorNotice message={params?.error || error?.message} />

      <section className="grid gap-4 md:grid-cols-4">
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Open tasks</p>
          <p className="mt-2 text-3xl font-semibold">{taskCount.count ?? 0}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Open issues</p>
          <p className="mt-2 text-3xl font-semibold">{issueCount.count ?? 0}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Submissions</p>
          <p className="mt-2 text-3xl font-semibold">{submissionCount.count ?? 0}</p>
        </article>
        <article className="rounded-lg border border-line bg-white p-5 shadow-panel">
          <p className="text-sm text-muted">Assets flagged</p>
          <p className="mt-2 text-3xl font-semibold">{assetCount.count ?? 0}</p>
        </article>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1fr_380px]">
        <SectionCard title="Report history" description="Workspace report records and source snapshots.">
          {reports?.length ? (
            <div className="space-y-4">
              {reports.map((report) => (
                <article key={report.id} className="rounded-lg border border-line p-4">
                  <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">
                    <div>
                      <p className="font-semibold">{report.title}</p>
                      <p className="mt-1 text-xs text-muted">
                        {report.report_type} · {report.date_range_start || "Start not set"} to {report.date_range_end || "End not set"} ·{" "}
                        {new Date(report.created_at).toLocaleDateString()}
                      </p>
                    </div>
                    <span className="rounded-full border border-blue-100 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">
                      Generated by Vaeroex
                    </span>
                  </div>
                  <div className="mt-4 max-h-64 overflow-auto rounded-lg bg-slate-50 p-4 text-sm leading-6 whitespace-pre-wrap">
                    {report.body_markdown || "No report body yet."}
                  </div>
                  <div className="mt-4">
                    <JsonPreview value={report.source_data_json} />
                  </div>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState title="No reports yet" description="Generate a weekly operations report once tasks, issues, forms, and asset checks are active." />
          )}
        </SectionCard>

        <SectionCard title="Create report" description="Vaeroex prompt checks run before report creation.">
          <form action={createReportAction} className="space-y-4">
            <TextInput label="Title" name="title" placeholder="Weekly Operations Report" />
            <SelectInput
              label="Report type"
              name="report_type"
              defaultValue="Weekly Operations Report"
              options={["Weekly Operations Report", "Daily Summary", "Bottleneck Review", "Readiness Snapshot"]}
            />
            <TextInput label="Date range start" name="date_range_start" type="date" />
            <TextInput label="Date range end" name="date_range_end" type="date" />
            <TextArea
              label="Report body"
              name="body_markdown"
              rows={10}
              placeholder={"# Weekly Operations Report\n\nGenerated by Vaeroex.\n\n## Executive Summary"}
            />
            <PrimaryButton>Create report</PrimaryButton>
          </form>
        </SectionCard>
      </section>
    </div>
  );
}
