export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type WorkspaceRole = "owner" | "admin" | "manager" | "staff" | "viewer";

export type Database = {
  public: {
    Functions: {
      accept_workspace_invites_for_current_user: {
        Args: Record<string, never>;
        Returns: void;
      };
      match_business_memory_chunks: {
        Args: {
          target_workspace_id: string;
          query_embedding: number[];
          match_count?: number;
          min_similarity?: number;
        };
        Returns: Array<{
          id: string;
          workspace_id: string;
          source_type: string;
          source_id: string | null;
          source_file_id: string | null;
          source_title: string;
          source_excerpt: string;
          summary: string | null;
          chunk_index: number;
          source_metadata: Json;
          source_quality: string;
          confidence_score: number;
          indexed_at: string;
          similarity: number;
        }>;
      };
    };
    Views: Record<string, never>;
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          full_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          industry: string | null;
          size: string | null;
          logo_url: string | null;
          primary_contact_name: string | null;
          primary_contact_email: string | null;
          created_by: string | null;
          subscription_status: string;
          plan_slug: string | null;
          subscription_required: boolean;
          trial_ends_at: string | null;
          manually_unlocked: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          industry?: string | null;
          size?: string | null;
          logo_url?: string | null;
          primary_contact_name?: string | null;
          primary_contact_email?: string | null;
          created_by?: string | null;
          subscription_status?: string;
          plan_slug?: string | null;
          subscription_required?: boolean;
          trial_ends_at?: string | null;
          manually_unlocked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspaces"]["Insert"]>;
        Relationships: [];
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string | null;
          role: WorkspaceRole;
          status: string;
          invited_email: string | null;
          invited_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id?: string | null;
          role: WorkspaceRole;
          status?: string;
          invited_email?: string | null;
          invited_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspace_members"]["Insert"]>;
        Relationships: [];
      };
      legal_acceptances: {
        Row: {
          id: string;
          user_id: string;
          workspace_id: string | null;
          terms_version: string;
          privacy_version: string;
          ai_disclaimer_version: string;
          sensitive_data_policy_version: string;
          accepted_at: string;
          user_email: string | null;
          user_agent: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          workspace_id?: string | null;
          terms_version: string;
          privacy_version: string;
          ai_disclaimer_version: string;
          sensitive_data_policy_version: string;
          accepted_at?: string;
          user_email?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["legal_acceptances"]["Insert"]>;
        Relationships: [];
      };
      business_intakes: {
        Row: {
          id: string;
          workspace_id: string;
          company_name: string | null;
          industry: string | null;
          team_size: string | null;
          locations: string | null;
          current_tools: string | null;
          biggest_operational_problems: string | null;
          repeated_missed_tasks: string | null;
          customer_followup_process: string | null;
          employee_accountability_process: string | null;
          reporting_process: string | null;
          equipment_or_asset_process: string | null;
          onboarding_process: string | null;
          ideal_outcome: string | null;
          monthly_budget_range: string | null;
          urgency_level: string | null;
          raw_answers_json: Json;
          ai_summary: string | null;
          ai_recommendations: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          company_name?: string | null;
          industry?: string | null;
          team_size?: string | null;
          locations?: string | null;
          current_tools?: string | null;
          biggest_operational_problems?: string | null;
          repeated_missed_tasks?: string | null;
          customer_followup_process?: string | null;
          employee_accountability_process?: string | null;
          reporting_process?: string | null;
          equipment_or_asset_process?: string | null;
          onboarding_process?: string | null;
          ideal_outcome?: string | null;
          monthly_budget_range?: string | null;
          urgency_level?: string | null;
          raw_answers_json?: Json;
          ai_summary?: string | null;
          ai_recommendations?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["business_intakes"]["Insert"]>;
        Relationships: [];
      };
      workflow_maps: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          department: string | null;
          trigger_event: string | null;
          steps_json: Json;
          owner_role: string | null;
          status: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          department?: string | null;
          trigger_event?: string | null;
          steps_json?: Json;
          owner_role?: string | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workflow_maps"]["Insert"]>;
        Relationships: [];
      };
      record_folders: {
        Row: {
          id: string;
          workspace_id: string;
          collection_type: string;
          name: string;
          created_by: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          collection_type: string;
          name: string;
          created_by?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["record_folders"]["Insert"]>;
        Relationships: [];
      };
      file_uploads: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          original_name: string;
          display_name: string;
          file_extension: string;
          mime_type: string;
          file_size_bytes: number;
          storage_bucket: string;
          storage_path: string;
          import_type: string;
          import_status: string;
          imported_rows: number;
          analysis_prompt: string | null;
          analysis_summary: string | null;
          processing_status: string;
          processing_error: string | null;
          processed_at: string | null;
          index_status: string;
          indexed_at: string | null;
          indexed_chunk_count: number;
          index_error: string | null;
          metadata_json: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          folder_id?: string | null;
          original_name: string;
          display_name: string;
          file_extension: string;
          mime_type: string;
          file_size_bytes?: number;
          storage_bucket?: string;
          storage_path: string;
          import_type?: string;
          import_status?: string;
          imported_rows?: number;
          analysis_prompt?: string | null;
          analysis_summary?: string | null;
          processing_status?: string;
          processing_error?: string | null;
          processed_at?: string | null;
          index_status?: string;
          indexed_at?: string | null;
          indexed_chunk_count?: number;
          index_error?: string | null;
          metadata_json?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["file_uploads"]["Insert"]>;
        Relationships: [];
      };
      file_imports: {
        Row: {
          id: string;
          workspace_id: string;
          file_upload_id: string;
          import_type: string;
          status: string;
          rows_total: number;
          rows_imported: number;
          mapping_json: Json;
          extraction_summary: string | null;
          errors_json: Json;
          reviewed_at: string | null;
          imported_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          file_upload_id: string;
          import_type: string;
          status?: string;
          rows_total?: number;
          rows_imported?: number;
          mapping_json?: Json;
          extraction_summary?: string | null;
          errors_json?: Json;
          reviewed_at?: string | null;
          imported_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["file_imports"]["Insert"]>;
        Relationships: [];
      };
      file_import_rows: {
        Row: {
          id: string;
          workspace_id: string;
          file_upload_id: string;
          import_id: string;
          import_type: string;
          row_number: number;
          data_json: Json;
          mapped_data_json: Json;
          validation_errors_json: Json;
          status: string;
          imported_record_type: string | null;
          imported_record_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          file_upload_id: string;
          import_id: string;
          import_type: string;
          row_number: number;
          data_json?: Json;
          mapped_data_json?: Json;
          validation_errors_json?: Json;
          status?: string;
          imported_record_type?: string | null;
          imported_record_id?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["file_import_rows"]["Insert"]>;
        Relationships: [];
      };
      file_processing_jobs: {
        Row: {
          id: string;
          workspace_id: string;
          file_upload_id: string;
          job_type: string;
          status: string;
          attempts: number;
          max_attempts: number;
          error_message: string | null;
          metadata_json: Json;
          queued_at: string;
          started_at: string | null;
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          file_upload_id: string;
          job_type?: string;
          status?: string;
          attempts?: number;
          max_attempts?: number;
          error_message?: string | null;
          metadata_json?: Json;
          queued_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["file_processing_jobs"]["Insert"]>;
        Relationships: [];
      };
      business_memory_chunks: {
        Row: {
          id: string;
          workspace_id: string;
          source_type: string;
          source_id: string | null;
          source_file_id: string | null;
          source_title: string;
          source_excerpt: string;
          summary: string | null;
          chunk_index: number;
          content_hash: string;
          embedding: number[] | null;
          embedding_model: string | null;
          source_metadata: Json;
          source_quality: string;
          confidence_score: number;
          token_estimate: number;
          indexed_at: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          source_type: string;
          source_id?: string | null;
          source_file_id?: string | null;
          source_title: string;
          source_excerpt: string;
          summary?: string | null;
          chunk_index?: number;
          content_hash: string;
          embedding?: number[] | null;
          embedding_model?: string | null;
          source_metadata?: Json;
          source_quality?: string;
          confidence_score?: number;
          token_estimate?: number;
          indexed_at?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["business_memory_chunks"]["Insert"]>;
        Relationships: [];
      };
      crm_leads: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          source_file_id: string | null;
          import_id: string | null;
          import_row_id: string | null;
          lead_name: string;
          company: string | null;
          email: string | null;
          phone: string | null;
          status: string;
          estimated_value: number | null;
          owner: string | null;
          notes: string | null;
          raw_data_json: Json;
          last_activity_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          folder_id?: string | null;
          source_file_id?: string | null;
          import_id?: string | null;
          import_row_id?: string | null;
          lead_name: string;
          company?: string | null;
          email?: string | null;
          phone?: string | null;
          status?: string;
          estimated_value?: number | null;
          owner?: string | null;
          notes?: string | null;
          raw_data_json?: Json;
          last_activity_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["crm_leads"]["Insert"]>;
        Relationships: [];
      };
      crm_lead_history: {
        Row: {
          id: string;
          workspace_id: string;
          lead_id: string;
          source_file_id: string | null;
          import_id: string | null;
          import_row_id: string | null;
          event_type: string;
          status: string | null;
          estimated_value: number | null;
          owner: string | null;
          notes: string | null;
          raw_data_json: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          lead_id: string;
          source_file_id?: string | null;
          import_id?: string | null;
          import_row_id?: string | null;
          event_type?: string;
          status?: string | null;
          estimated_value?: number | null;
          owner?: string | null;
          notes?: string | null;
          raw_data_json?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["crm_lead_history"]["Insert"]>;
        Relationships: [];
      };
      operational_metrics: {
        Row: {
          id: string;
          workspace_id: string;
          source_file_id: string | null;
          import_id: string | null;
          import_row_id: string | null;
          metric_name: string;
          category: string | null;
          value: number | null;
          metric_date: string;
          owner: string | null;
          notes: string | null;
          raw_data_json: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          source_file_id?: string | null;
          import_id?: string | null;
          import_row_id?: string | null;
          metric_name: string;
          category?: string | null;
          value?: number | null;
          metric_date?: string;
          owner?: string | null;
          notes?: string | null;
          raw_data_json?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["operational_metrics"]["Insert"]>;
        Relationships: [];
      };
      forms: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          form_type: string | null;
          schema_json: Json;
          is_public: boolean;
          public_slug: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          form_type?: string | null;
          schema_json?: Json;
          is_public?: boolean;
          public_slug?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["forms"]["Insert"]>;
        Relationships: [];
      };
      form_submissions: {
        Row: {
          id: string;
          workspace_id: string;
          form_id: string;
          submitted_by: string | null;
          submitter_name: string | null;
          submitter_email: string | null;
          data_json: Json;
          ai_summary: string | null;
          ai_detected_priority: string | null;
          ai_detected_followups_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          form_id: string;
          submitted_by?: string | null;
          submitter_name?: string | null;
          submitter_email?: string | null;
          data_json?: Json;
          ai_summary?: string | null;
          ai_detected_priority?: string | null;
          ai_detected_followups_json?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["form_submissions"]["Insert"]>;
        Relationships: [];
      };
      checklists: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          category: string | null;
          frequency: string | null;
          items_json: Json;
          assigned_role: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          category?: string | null;
          frequency?: string | null;
          items_json?: Json;
          assigned_role?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["checklists"]["Insert"]>;
        Relationships: [];
      };
      checklist_runs: {
        Row: {
          id: string;
          workspace_id: string;
          checklist_id: string;
          assigned_to: string | null;
          assigned_person_id: string | null;
          assigned_role: string | null;
          assigned_department: string | null;
          status: string;
          responses_json: Json;
          notes: string | null;
          due_date: string | null;
          priority: string;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          checklist_id: string;
          assigned_to?: string | null;
          assigned_person_id?: string | null;
          assigned_role?: string | null;
          assigned_department?: string | null;
          status?: string;
          responses_json?: Json;
          notes?: string | null;
          due_date?: string | null;
          priority?: string;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["checklist_runs"]["Insert"]>;
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          description: string | null;
          status: string;
          priority: string;
          category: string | null;
          assigned_to: string | null;
          assigned_person_id: string | null;
          assigned_role: string | null;
          assigned_department: string | null;
          due_date: string | null;
          related_type: string | null;
          related_id: string | null;
          ai_generated: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          description?: string | null;
          status?: string;
          priority?: string;
          category?: string | null;
          assigned_to?: string | null;
          assigned_person_id?: string | null;
          assigned_role?: string | null;
          assigned_department?: string | null;
          due_date?: string | null;
          related_type?: string | null;
          related_id?: string | null;
          ai_generated?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tasks"]["Insert"]>;
        Relationships: [];
      };
      kpis: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          name: string;
          category: string | null;
          target: number | null;
          actual_value: number | null;
          metric_date: string;
          owner: string | null;
          notes: string | null;
          source: string | null;
          source_file_id: string | null;
          import_id: string | null;
          import_row_id: string | null;
          raw_data_json: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          folder_id?: string | null;
          name: string;
          category?: string | null;
          target?: number | null;
          actual_value?: number | null;
          metric_date?: string;
          owner?: string | null;
          notes?: string | null;
          source?: string | null;
          source_file_id?: string | null;
          import_id?: string | null;
          import_row_id?: string | null;
          raw_data_json?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["kpis"]["Insert"]>;
        Relationships: [];
      };
      kpi_settings: {
        Row: {
          id: string;
          workspace_id: string;
          kpi_name: string;
          category: string | null;
          target: number | null;
          weight: number;
          definition: string | null;
          color: string;
          is_visible: boolean;
          sort_order: number;
          unit_type: string | null;
          display_unit: string | null;
          value_format: string | null;
          x_axis_label: string | null;
          y_axis_label: string | null;
          preferred_chart_type: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          kpi_name: string;
          category?: string | null;
          target?: number | null;
          weight?: number;
          definition?: string | null;
          color?: string;
          is_visible?: boolean;
          sort_order?: number;
          unit_type?: string | null;
          display_unit?: string | null;
          value_format?: string | null;
          x_axis_label?: string | null;
          y_axis_label?: string | null;
          preferred_chart_type?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["kpi_settings"]["Insert"]>;
        Relationships: [];
      };
      issues: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          description: string | null;
          issue_type: string | null;
          severity: string;
          status: string;
          root_cause: string | null;
          recommended_fix: string | null;
          assigned_to: string | null;
          assigned_person_id: string | null;
          assigned_role: string | null;
          assigned_department: string | null;
          due_date: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          description?: string | null;
          issue_type?: string | null;
          severity?: string;
          status?: string;
          root_cause?: string | null;
          recommended_fix?: string | null;
          assigned_to?: string | null;
          assigned_person_id?: string | null;
          assigned_role?: string | null;
          assigned_department?: string | null;
          due_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["issues"]["Insert"]>;
        Relationships: [];
      };
      assets: {
        Row: {
          id: string;
          workspace_id: string;
          asset_name: string;
          asset_type: string | null;
          identifier: string | null;
          location: string | null;
          status: string;
          assigned_to: string | null;
          last_checked_at: string | null;
          notes: string | null;
          folder_id: string | null;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          asset_name: string;
          asset_type?: string | null;
          identifier?: string | null;
          location?: string | null;
          status?: string;
          assigned_to?: string | null;
          last_checked_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["assets"]["Insert"]>;
        Relationships: [];
      };
      asset_checks: {
        Row: {
          id: string;
          workspace_id: string;
          asset_id: string;
          checked_by: string | null;
          status: string;
          notes: string | null;
          photos_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          asset_id: string;
          checked_by?: string | null;
          status: string;
          notes?: string | null;
          photos_json?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["asset_checks"]["Insert"]>;
        Relationships: [];
      };
      people: {
        Row: {
          id: string;
          workspace_id: string;
          full_name: string;
          email: string | null;
          phone: string | null;
          role_title: string | null;
          department: string | null;
          status: string;
          start_date: string | null;
          notes: string | null;
          folder_id: string | null;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          role_title?: string | null;
          department?: string | null;
          status?: string;
          start_date?: string | null;
          notes?: string | null;
          folder_id?: string | null;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["people"]["Insert"]>;
        Relationships: [];
      };
      sops: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          department: string | null;
          category: string | null;
          body_markdown: string | null;
          status: string;
          version: number;
          created_by: string | null;
          ai_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          department?: string | null;
          category?: string | null;
          body_markdown?: string | null;
          status?: string;
          version?: number;
          created_by?: string | null;
          ai_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sops"]["Insert"]>;
        Relationships: [];
      };
      reports: {
        Row: {
          id: string;
          workspace_id: string;
          report_type: string;
          title: string;
          date_range_start: string | null;
          date_range_end: string | null;
          body_markdown: string | null;
          source_data_json: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          report_type: string;
          title: string;
          date_range_start?: string | null;
          date_range_end?: string | null;
          body_markdown?: string | null;
          source_data_json?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["reports"]["Insert"]>;
        Relationships: [];
      };
      ai_agent_runs: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          agent_type: string;
          input_json: Json;
          output_json: Json;
          status: string;
          error_message: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          folder_id?: string | null;
          agent_type: string;
          input_json?: Json;
          output_json?: Json;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ai_agent_runs"]["Insert"]>;
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string | null;
          type: string;
          title: string;
          body: string | null;
          priority: string;
          related_module: string | null;
          related_record_type: string | null;
          related_record_id: string | null;
          action_label: string | null;
          action_href: string | null;
          recipient_scope: string;
          recipient_person_id: string | null;
          recipient_role: string | null;
          recipient_department: string | null;
          metadata_json: Json;
          read_at: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id?: string | null;
          type: string;
          title: string;
          body?: string | null;
          priority?: string;
          related_module?: string | null;
          related_record_type?: string | null;
          related_record_id?: string | null;
          action_label?: string | null;
          action_href?: string | null;
          recipient_scope?: string;
          recipient_person_id?: string | null;
          recipient_role?: string | null;
          recipient_department?: string | null;
          metadata_json?: Json;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["notifications"]["Insert"]>;
        Relationships: [];
      };
      record_shares: {
        Row: {
          id: string;
          workspace_id: string;
          source_type: string;
          source_id: string;
          source_title: string;
          share_scope: string;
          person_id: string | null;
          role: string | null;
          department: string | null;
          message: string | null;
          distribution_schedule: string;
          last_shared_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          source_type: string;
          source_id: string;
          source_title: string;
          share_scope?: string;
          person_id?: string | null;
          role?: string | null;
          department?: string | null;
          message?: string | null;
          distribution_schedule?: string;
          last_shared_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["record_shares"]["Insert"]>;
        Relationships: [];
      };
      operational_assignments: {
        Row: {
          id: string;
          workspace_id: string;
          source_type: string;
          source_id: string | null;
          source_title: string | null;
          title: string;
          description: string | null;
          assigned_person_id: string | null;
          assigned_role: string | null;
          assigned_department: string | null;
          due_date: string | null;
          priority: string;
          status: string;
          created_by: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          source_type: string;
          source_id?: string | null;
          source_title?: string | null;
          title: string;
          description?: string | null;
          assigned_person_id?: string | null;
          assigned_role?: string | null;
          assigned_department?: string | null;
          due_date?: string | null;
          priority?: string;
          status?: string;
          created_by?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["operational_assignments"]["Insert"]>;
        Relationships: [];
      };
      business_decisions: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          reason: string | null;
          expected_outcome: string | null;
          related_kpi: string | null;
          related_report_id: string | null;
          related_issue_id: string | null;
          related_sop_id: string | null;
          owner: string | null;
          review_date: string | null;
          status: string;
          outcome_summary: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          reason?: string | null;
          expected_outcome?: string | null;
          related_kpi?: string | null;
          related_report_id?: string | null;
          related_issue_id?: string | null;
          related_sop_id?: string | null;
          owner?: string | null;
          review_date?: string | null;
          status?: string;
          outcome_summary?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["business_decisions"]["Insert"]>;
        Relationships: [];
      };
      vaeroex_recommendation_outcomes: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          source_type: string;
          source_id: string | null;
          source_title: string | null;
          evidence: string | null;
          related_module: string | null;
          related_kpi: string | null;
          related_report_id: string | null;
          related_file_id: string | null;
          related_issue_id: string | null;
          related_task_id: string | null;
          expected_outcome: string | null;
          created_action_type: string | null;
          created_action_id: string | null;
          owner: string | null;
          priority: string;
          review_date: string | null;
          status: string;
          outcome_summary: string | null;
          metadata_json: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          source_type?: string;
          source_id?: string | null;
          source_title?: string | null;
          evidence?: string | null;
          related_module?: string | null;
          related_kpi?: string | null;
          related_report_id?: string | null;
          related_file_id?: string | null;
          related_issue_id?: string | null;
          related_task_id?: string | null;
          expected_outcome?: string | null;
          created_action_type?: string | null;
          created_action_id?: string | null;
          owner?: string | null;
          priority?: string;
          review_date?: string | null;
          status?: string;
          outcome_summary?: string | null;
          metadata_json?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["vaeroex_recommendation_outcomes"]["Insert"]>;
        Relationships: [];
      };
      kpi_alert_rules: {
        Row: {
          id: string;
          workspace_id: string;
          kpi_name: string;
          condition_type: string;
          threshold_value: number | null;
          recipient_scope: string;
          person_id: string | null;
          role: string | null;
          department: string | null;
          priority: string;
          is_active: boolean;
          created_by: string | null;
          last_triggered_at: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          kpi_name: string;
          condition_type: string;
          threshold_value?: number | null;
          recipient_scope?: string;
          person_id?: string | null;
          role?: string | null;
          department?: string | null;
          priority?: string;
          is_active?: boolean;
          created_by?: string | null;
          last_triggered_at?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["kpi_alert_rules"]["Insert"]>;
        Relationships: [];
      };
      kpi_alert_events: {
        Row: {
          id: string;
          workspace_id: string;
          rule_id: string | null;
          kpi_id: string | null;
          title: string;
          message: string;
          priority: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          rule_id?: string | null;
          kpi_id?: string | null;
          title: string;
          message: string;
          priority?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["kpi_alert_events"]["Insert"]>;
        Relationships: [];
      };
      report_subscription_preferences: {
        Row: {
          id: string;
          workspace_id: string;
          category: string;
          preference_scope: string;
          person_id: string | null;
          role: string | null;
          email_status: string;
          pause_until: string | null;
          schedule_day_of_week: number | null;
          schedule_day_kind: string;
          schedule_day_of_month: number | null;
          schedule_month_in_quarter: number | null;
          schedule_time: string | null;
          last_generated_at: string | null;
          last_notified_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          category: string;
          preference_scope?: string;
          person_id?: string | null;
          role?: string | null;
          email_status?: string;
          pause_until?: string | null;
          schedule_day_of_week?: number | null;
          schedule_day_kind?: string;
          schedule_day_of_month?: number | null;
          schedule_month_in_quarter?: number | null;
          schedule_time?: string | null;
          last_generated_at?: string | null;
          last_notified_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["report_subscription_preferences"]["Insert"]>;
        Relationships: [];
      };
      scheduled_report_runs: {
        Row: {
          id: string;
          workspace_id: string;
          category: string;
          report_id: string | null;
          run_date: string;
          status: string;
          started_at: string;
          completed_at: string | null;
          error_message: string | null;
          metadata_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          category: string;
          report_id?: string | null;
          run_date: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          error_message?: string | null;
          metadata_json?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["scheduled_report_runs"]["Insert"]>;
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          workspace_id: string;
          actor_user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          metadata_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          actor_user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          metadata_json?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["audit_logs"]["Insert"]>;
        Relationships: [];
      };
      subscription_plans: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          monthly_price_cents: number | null;
          annual_price_cents: number | null;
          max_workspaces: number | null;
          max_users: number | null;
          max_forms: number | null;
          max_checklists: number | null;
          max_ai_runs_per_month: number | null;
          features_json: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          monthly_price_cents?: number | null;
          annual_price_cents?: number | null;
          max_workspaces?: number | null;
          max_users?: number | null;
          max_forms?: number | null;
          max_checklists?: number | null;
          max_ai_runs_per_month?: number | null;
          features_json?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["subscription_plans"]["Insert"]>;
        Relationships: [];
      };
      customer_subscriptions: {
        Row: {
          id: string;
          user_id: string | null;
          workspace_id: string | null;
          customer_email: string;
          customer_name: string | null;
          source: string;
          billing_provider: string;
          plan_slug: string | null;
          status: string;
          squarespace_order_id: string | null;
          squarespace_customer_id: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          stripe_current_period_end: string | null;
          stripe_cancel_at_period_end: boolean;
          onboarding_email_status: string;
          onboarding_email_sent_at: string | null;
          onboarding_email_message_id: string | null;
          onboarding_email_error: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          canceled_at: string | null;
          last_payment_at: string | null;
          raw_payload_json: Json;
          manually_activated: boolean;
          manually_activated_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          workspace_id?: string | null;
          customer_email: string;
          customer_name?: string | null;
          source?: string;
          billing_provider?: string;
          plan_slug?: string | null;
          status?: string;
          squarespace_order_id?: string | null;
          squarespace_customer_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          stripe_current_period_end?: string | null;
          stripe_cancel_at_period_end?: boolean;
          onboarding_email_status?: string;
          onboarding_email_sent_at?: string | null;
          onboarding_email_message_id?: string | null;
          onboarding_email_error?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          canceled_at?: string | null;
          last_payment_at?: string | null;
          raw_payload_json?: Json;
          manually_activated?: boolean;
          manually_activated_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["customer_subscriptions"]["Insert"]>;
        Relationships: [];
      };
      subscription_events: {
        Row: {
          id: string;
          source: string;
          billing_provider: string | null;
          event_type: string | null;
          customer_email: string | null;
          squarespace_order_id: string | null;
          stripe_event_id: string | null;
          stripe_subscription_id: string | null;
          payload_json: Json;
          processed: boolean;
          processing_error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source?: string;
          billing_provider?: string | null;
          event_type?: string | null;
          customer_email?: string | null;
          squarespace_order_id?: string | null;
          stripe_event_id?: string | null;
          stripe_subscription_id?: string | null;
          payload_json?: Json;
          processed?: boolean;
          processing_error?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["subscription_events"]["Insert"]>;
        Relationships: [];
      };
      ai_usage: {
        Row: {
          id: string;
          workspace_id: string | null;
          user_id: string | null;
          agent_type: string | null;
          tokens_used: number;
          estimated_cost_cents: number;
          model: string | null;
          input_tokens: number;
          output_tokens: number;
          request_id: string | null;
          latency_ms: number | null;
          status: string;
          metadata_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          user_id?: string | null;
          agent_type?: string | null;
          tokens_used?: number;
          estimated_cost_cents?: number;
          model?: string | null;
          input_tokens?: number;
          output_tokens?: number;
          request_id?: string | null;
          latency_ms?: number | null;
          status?: string;
          metadata_json?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ai_usage"]["Insert"]>;
        Relationships: [];
      };
      manual_activation_requests: {
        Row: {
          id: string;
          name: string;
          email: string;
          company: string | null;
          plan_purchased: string | null;
          order_number: string | null;
          message: string | null;
          status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          company?: string | null;
          plan_purchased?: string | null;
          order_number?: string | null;
          message?: string | null;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["manual_activation_requests"]["Insert"]>;
        Relationships: [];
      };
      support_requests: {
        Row: {
          id: string;
          workspace_id: string | null;
          user_id: string | null;
          name: string;
          email: string;
          issue_type: string;
          message: string;
          priority: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          user_id?: string | null;
          name: string;
          email: string;
          issue_type: string;
          message: string;
          priority?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["support_requests"]["Insert"]>;
        Relationships: [];
      };
    };
  };
};

export type Workspace = Database["public"]["Tables"]["workspaces"]["Row"];
export type WorkspaceMember = Database["public"]["Tables"]["workspace_members"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
