import { createSopAction } from "@/app/app/operations/actions";
import { EmptyState } from "@/components/operations/EmptyState";
import { ErrorNotice } from "@/components/operations/ErrorNotice";
import { PrimaryButton, SelectInput, TextArea, TextInput } from "@/components/operations/FormControls";
import { PageHeader } from "@/components/operations/PageHeader";
import { SectionCard } from "@/components/operations/SectionCard";
import { StatusBadge } from "@/components/operations/StatusBadge";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

type SopsPageProps = {
  searchParams?: Promise<{ error?: string }>;
};

export default async function SopsPage({ searchParams }: SopsPageProps) {
  const params = await searchParams;
  const { supabase, workspaceId } = await requireWorkspacePage();
  const { data: sops, error } = await supabase
    .from("sops")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="SOPs"
        title="Standard operating procedures"
        description="Draft, review, and maintain step-by-step operating procedures. Vaeroex-generated drafts remain clearly labeled for manager review."
      />

      <ErrorNotice message={params?.error || error?.message} />

      <section className="grid gap-6 xl:grid-cols-[1fr_380px]">
        <SectionCard title="SOP library" description="Versioned procedures for repeatable work.">
          {sops?.length ? (
            <div className="space-y-4">
              {sops.map((sop) => (
                <article key={sop.id} className="rounded-lg border border-line p-4">
                  <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                    <div>
                      <p className="font-semibold">{sop.title}</p>
                      <p className="mt-1 text-xs text-muted">
                        {sop.department || "General"} · {sop.category || "Uncategorized"} · Version {sop.version}
                        {sop.ai_generated ? " · Generated by Vaeroex" : ""}
                      </p>
                    </div>
                    <StatusBadge value={sop.status} />
                  </div>
                  <div className="mt-4 max-h-56 overflow-auto rounded-lg bg-slate-50 p-4 text-sm leading-6 whitespace-pre-wrap">
                    {sop.body_markdown || "No SOP body yet."}
                  </div>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState title="No SOPs yet" description="Create a procedure for recurring work, handoffs, quality review, onboarding, or customer follow-up." />
          )}
        </SectionCard>

        <SectionCard title="Create SOP" description="Start with a practical draft that managers can review.">
          <form action={createSopAction} className="space-y-4">
            <TextInput label="Title" name="title" required />
            <TextInput label="Department" name="department" />
            <TextInput label="Category" name="category" />
            <SelectInput label="Status" name="status" defaultValue="Draft" options={["Draft", "In review", "Approved", "Archived"]} />
            <TextInput label="Version" name="version" type="number" defaultValue={1} />
            <TextArea
              label="Procedure"
              name="body_markdown"
              rows={10}
              placeholder={"Purpose\nScope\nSteps\nQuality checks\nEscalation path"}
            />
            <PrimaryButton>Create SOP</PrimaryButton>
          </form>
        </SectionCard>
      </section>
    </div>
  );
}
