import { createSopAction } from "@/app/app/operations/actions";
import { CreateDrawer } from "@/components/operations/CreateDrawer";
import { ErrorNotice } from "@/components/operations/ErrorNotice";
import { PrimaryButton, SelectInput, TextArea, TextInput } from "@/components/operations/FormControls";
import { ManagedRecordList, type ManagedRecordEditField } from "@/components/operations/ManagedRecordList";
import { PageHeader } from "@/components/operations/PageHeader";
import { SectionCard } from "@/components/operations/SectionCard";
import { getRecordFolders, managedValues, shortPreview } from "@/lib/records/management";
import { requireWorkspacePage } from "@/lib/workspaces/page-context";

type SopsPageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

const sopStatuses = ["Draft", "In review", "Approved", "Archived"];
const sopEditFields: ManagedRecordEditField[] = [
  { name: "title", label: "Title", required: true },
  { name: "department", label: "Department" },
  { name: "category", label: "Category" },
  { name: "status", label: "Status", type: "select", options: sopStatuses },
  { name: "version", label: "Version", type: "number" },
  { name: "body_markdown", label: "Procedure", type: "textarea", rows: 10 }
];

export default async function SopsPage({ searchParams }: SopsPageProps) {
  const params = await searchParams;
  const { supabase, workspaceId } = await requireWorkspacePage();
  const [{ data: sops, error }, folderResult] = await Promise.all([
    supabase
      .from("sops")
      .select("*")
      .eq("workspace_id", workspaceId)
      .order("created_at", { ascending: false }),
    getRecordFolders(supabase, workspaceId, "sops")
  ]);
  const managedSops = (sops || []).map((sop) => {
    const management = managedValues(sop);

    return {
      id: sop.id,
      title: sop.title,
      type: sop.ai_generated ? "Vaeroex SOP draft" : "SOP",
      status: sop.status,
      owner: sop.department || "General",
      category: sop.category || "Uncategorized",
      createdAt: sop.created_at,
      updatedAt: management.updatedAt || sop.updated_at,
      folderId: management.folderId,
      archivedAt: management.archivedAt,
      deletedAt: management.deletedAt,
      preview: shortPreview(sop.body_markdown, "No SOP body yet."),
      meta: [
        { label: "Department", value: sop.department || "General" },
        { label: "Version", value: sop.version },
        { label: "Source", value: sop.ai_generated ? "Generated by Vaeroex" : "Manual" }
      ],
      editFields: sopEditFields,
      editValues: {
        title: sop.title,
        department: sop.department,
        category: sop.category,
        status: sop.status,
        version: sop.version,
        body_markdown: sop.body_markdown
      },
      children: <div className="whitespace-pre-wrap text-sm leading-6 text-muted">{sop.body_markdown || "No SOP body yet."}</div>
    };
  });

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="SOPs"
        title="SOP Library"
        description="Draft, review, and maintain step-by-step working procedures. Vaeroex-generated drafts remain clearly labeled for manager review."
      />

      <ErrorNotice message={(params?.error as string | undefined) || error?.message || folderResult.error?.message} />

      <section className="space-y-6">
        <CreateDrawer title="Create SOP" description="Start with a practical draft that managers can review." triggerLabel="New SOP">
          <form action={createSopAction} className="grid gap-4 lg:grid-cols-2">
            <TextInput label="Title" name="title" required />
            <TextInput label="Department" name="department" />
            <TextInput label="Category" name="category" />
            <SelectInput label="Status" name="status" defaultValue="Draft" options={sopStatuses} />
            <TextInput label="Version" name="version" type="number" defaultValue={1} />
            <div className="lg:col-span-2">
              <TextArea
                label="Procedure"
                name="body_markdown"
                rows={8}
                placeholder={"Purpose\nScope\nSteps\nQuality checks\nEscalation path"}
              />
            </div>
            <div className="lg:col-span-2">
              <PrimaryButton>Create SOP</PrimaryButton>
            </div>
          </form>
        </CreateDrawer>

        <SectionCard title="SOP library" description="Versioned procedures that support consistent execution.">
          <ManagedRecordList
            collection="sops"
            records={managedSops}
            folders={folderResult.folders}
            title="SOP records"
            description="Keep procedures collapsed until a manager needs to view or edit the details."
            emptyTitle="No SOPs yet"
            emptyDescription="Create a procedure for recurring work, handoffs, quality review, onboarding, or customer follow-up."
            searchParams={params}
          />
        </SectionCard>

      </section>
    </div>
  );
}
